# Equal Weighted Like Portfolio - comparisons

This example compares the performance of an equal weighted portfolio relative to several risk-based optimal portfolios with similar risk profile. 

The CVaR, SMCR, EVaR, MAD, LSD, BTAD, BTSD, GINI, SD and MV risk-based portfolios are considered. We use the `rtype=InvNrisk` optimization flag (the optimal portfolio with the same risk as the equal weights portfolio).

The results are presented below. We concluded that, at least for the data in this example, there is no clear-cut preference for a portfolio construction (with a superior performance under all market conditions).


We start by importing **azapy** and other useful packages.

In [1]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0", flush=True)

azapy version 1.2.6 >= 1.2.0

### Collect historical market data

- `symb` is the list of stock symbols (portfolio components).
- `sdate` and `edate` are the start and end dates of historical time-series.
- `mktdir` is the name of the directory used as a buffer for market data collected from the data provider (in this case _alphavantage_).
    
> Note: if the flag `force=False` then a reading from `dir=mktdir` is attempted. If it fails, then the data provider servers will be accessed. The new data will be saved to the `dir=mktdir`. For more information see the readMkT documentation https://azapy.readthedocs.io/en/latest/.

In [2]:
symb = ['GLD', 'TLT', 'XLV', 'SPY', 'VHT']

sdate = "2012-01-01"
edate = "today"
mktdir = "../MkTdata"

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

read GLD data from file
get GLD updates from yahoo
save GLD updated data to file
read TLT data from file
get TLT updates from yahoo
save TLT updated data to file
read XLV data from file
get XLV updates from yahoo
save XLV updated data to file
read SPY data from file
get SPY updates from yahoo
save SPY updated data to file
read VHT data from file
get VHT updates from yahoo
save VHT updated data to file

Request between 2012-01-03 : 2026-05-06
                    GLD         TLT         XLV         SPY         VHT
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3606        3606        3606        3606        3606
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2026-05-06  2026-05-06  2026-05-06  2026-05-06  2026-05-06
error                No          No          No          No          No
extraction time 3.13 s

### Set scenarios model parameters

Since we plan to run many scenarios, it is useful to organize their model parameters in a dictionary.
The keys are the portfolio names, and the values are the model parameters organized also as dictionaries:
- 'type' : is the portfolio class used in the simulation,
- 'm_param' : is a dictionary with parameters for `set_model` functions.

Note that:
- `'P_N'` is the reference equal weighted portfolio (EWP),
- `'P_CVaR'` is the mCVaR optimal portfolio with confidence levels `alpha_CVaR` equal weighted,
- `'P_SMCR'` is the mSMCR optimal portfolio with confidence levels `alpha_SMCR` equal weighted,
- `'P_EVaR'` is the mEVaR optimal portfolio with confidence levels `alpha_EVaR` equal weighted,
- `'P_MAD'` is the mMAD optimal portfolio with weights `coef_MAD`,
- `'P_LSD'` is the mLSD optimal portfolio with weights `coef_LSD`,
- `'P_BTAD'` is the mBTAD optimal portfolio with threshold levels `alpha_BTAD` equal weighted,
- `'P_BTSD'` is the mBTSD optimal portfolio with threshold levels `alpha_BTSD` equal weighted,
- `'P_MV'` is the MV (mean-variance) optimal portfolio,
- `'P_SD'` is the SD optimal portfolio.
- `'P_Gini'` is the Gini optimal portfolio. It is commented out in the `models` dictionary since it is very slow.
- In all cases the optimization type is set to `rtype='InvNRisk'` (optimal portfolio with the same risk profile as the equal weighted portfolio)
- The `'hlength'` parameter (the length of historical data used in weights calibration) is set to 3.25 years except for `'P_GINI'` where it is set to 1.25 years (for computational speed convenience).

> In this case P_MV and P_SD are the same.

In [3]:
rtype = 'InvNrisk'
alpha_CVaR = [0.95, 0.90, 0.85]
alpha_SMCR = [0.9, 0.80]
alpha_EVaR = [0.75, 0.65]
coef_MAD = [1./3.] * 3
coef_LSD = [1./3.] * 3
alpha_BTAD = [-0.01, 0]
alpha_BTSD = [-0.01, 0]
hlength = 1.25
verbose = False

models = {'P_CVaR': {'type': 'Port_CVaR', 'm_param': {'alpha': alpha_CVaR, 'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          'P_SMCR': {'type': 'Port_SMCR', 'm_param': {'alpha': alpha_SMCR, 'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          'P_EVaR': {'type': 'Port_EVaR', 'm_param': {'alpha': alpha_EVaR, 'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          'P_MAD': {'type': 'Port_MAD', 'm_param': {'coef': coef_MAD, 'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          'P_LSD': {'type': 'Port_LSD', 'm_param': {'coef': coef_LSD, 'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          'P_BTAD': {'type': 'Port_BTAD', 'm_param': {'alpha': alpha_BTAD, 'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          'P_BTSD': {'type': 'Port_BTSD', 'm_param': {'alpha': alpha_BTSD, 'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          #'P_GINI': {'type': 'Port_GINI', 'm_param': {'rtype': rtype, 'hlength': 1.25, 'verbose': verbose}},
          'P_MV': {'type': 'Port_MV', 'm_param': {'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          'P_SD': {'type': 'Port_SD', 'm_param': {'rtype': rtype, 'hlength': hlength, 'verbose': verbose}},
          'P_N': {'type': 'Port_ConstW', 'm_param': {'ww': None}}}

### Main computation loop

- `port` is a list containing the simulated time-series. We will use it to setup a simple portfolio *(see the documentation for `Port_Simple` class)*. It is a very convenient way to facilitate the visual and numerical comparisons between these portfolio performances. 
- `pp` is a dictionary holding the portfolio objects. They may be used later for further analytical inquires.

In [4]:
port = []
pp = {}
for key, val in models.items():
    ppz = getattr(az, val['type'])
    pp_ = ppz(mktdata, pname=key)
    pp[key] = pp_
    port_ = pp_.set_model(**val['m_param'])
    port.append(port_)

### Prepare the results for comparisons 

Build a `Port_Simple` class holding all the computed portfolios as components. We use this structure to build comparative graphical and numerical performance reports. The aggregated portfolio of portfolios time-series will be neglected.

>Note the call to `set_model` method that is a must.

>Observation: `Port_Simple` is the class that supports the back testing of "Buy and Hold" portfolio (_see its documentation_).
It also can be used as a tool to compare the performance of multiple portfolios. Here we use it in this latter capacity.

In [5]:
ps = az.Port_Simple(port, col='close', pname='ALL')
_ = ps.set_model()

### Time-series visualization 

We used the flag `componly=True` to plot only the portfolio components.

In [6]:
_ = ps.port_view_all(componly=True, fancy=True, title="Relative performance")

### Portfolio performances

Note that, at least for the duration of this simulation, the P_BTAD portfolio has a similar rate of returns as 
P_N. However, P_BTAD has higher maximum drawdown than P_N. P_N has the smallest maximum drawdown among all portfolios. 

> Note: in this case P_MV anf P_SD portfolios are the same.

In [7]:
ps.port_perf(componly=True, fancy=True)

           RR      DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
P_CVaR  11.28  -17.33  0.651179  2026-03-30  2026-01-29         NaN       97
P_LSD   11.30  -17.47  0.646717  2026-03-30  2026-01-29         NaN       97
P_EVaR  11.30  -17.59  0.641985  2026-03-30  2026-01-29         NaN       97
P_BTSD  11.06  -17.55  0.630257  2026-03-30  2026-01-29         NaN       97
P_MAD   10.96  -18.74  0.584842  2022-09-30  2022-01-03  2024-02-07      765
P_MV    10.88  -19.00  0.572343  2022-09-30  2022-01-03  2024-01-25      752
P_SD    10.88  -19.00  0.572343  2022-09-30  2022-01-03  2024-01-25      752
P_BTAD  10.78  -20.11  0.536082  2022-09-30  2022-01-03  2024-02-22      780
P_N      9.04  -19.16  0.471885  2022-10-20  2021-12-30  2024-02-23      785
P_SMCR  10.33 -100.00  0.103343  2018-06-27  2018-01-26  2020-01-27      731

### Annual returns

Remarks:

- 2015 (only half year in this simulation) and 2016, P_N is the best performer.
- 2016 P_N is the best while P_GINI is the worst.
- 2017 P_N is the worst performer. The best performers are P_GINI.
- 2018 P_GINI has the best performance. P_N is second.
- 2019 The best performers are P_BTAD closely follow by P_CVaR, P_MAD and P_LSD. P_GINI and P_N are the worst.
- 2020 The best performers are P_GINI follow by P_N.
- 2021 (first half of the year in this simulation) P_GINI is the leader followed by P_N and P_MV (P_SD is the same with P_MV).

Conclusion: Depending on the historical period P_N may be an outperformer or an underperformer. Moreover, similar remarks can be made about any other portfolio strategy.

> Note: the flags `withcomp=True` includes the portfolios components while the flag `componly=True` excludes the aggregated portfolio of portfolios.

In [18]:
ps.port_annual_returns(withcomp=True, componly=True, fancy=True)

c:\Users\mirce\anaconda3\envs\wk_3_14_4\Lib\site-packages\numpy\_core\_methods.py:53: RuntimeWarning: invalid value encountered in reduce
  return umr_prod(a, axis, dtype, out, keepdims, initial, where)

### Monthly returns

> Note: the flags `withcomp=True` includes the portfolios components while the flag `componly=True` excludes the aggregated portfolio.

In [9]:
ps.port_monthly_returns(withcomp=True, componly=True, fancy=True)

### A closer look at P_BTAD portfolio

Monthly returns: are volatile.

In [10]:
pp['P_BTAD'].port_monthly_returns(fancy=True)

### P_BTAD performance

An example of individual portfolio performance inquiry.

In [11]:
pp['P_BTAD'].port_perf(fancy=True)

           RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
P_BTAD  10.78 -20.11  0.536082  2022-09-30  2022-01-03  2024-02-22      780
SPY     15.00 -33.72  0.444895  2020-03-23  2020-02-19  2020-08-10      173
XLV     12.28 -28.40  0.432239  2020-03-23  2020-01-22  2020-07-15      175
VHT     12.40 -28.85  0.429660  2020-03-23  2020-02-19  2020-06-08      110
GLD      7.36 -42.11  0.174853  2015-12-17  2012-10-04  2020-07-22     2848
TLT      0.47 -48.35  0.009628  2023-10-19  2020-08-04         NaN     2101

### P_BTAD drawdowns

Remarks: The first 2 largest drawdowns are similar. However, the 2018 drawdown was caused by the unexpected Feds rate increase while the 2020 event is the Covid-19 pandemic crash.

In [12]:
pp['P_BTAD'].port_drawdown(fancy=True)

       DD        Date       Start         End  NrDays
No
1  -20.11  2022-09-30  2022-01-03  2024-02-22     780
2  -18.73  2016-12-14  2016-07-08  2017-12-11     521
3  -17.84  2026-03-30  2026-01-29         NaN      97
4  -17.49  2015-09-28  2015-07-16  2016-07-06     356
5  -14.97  2020-03-18  2020-03-06  2020-04-15      40

### P_BTAD weights

Remarks: At present the P_BTAD portfolio is dominated by GLD and VGT.

In [13]:
pp['P_BTAD'].get_weights(fancy=True)

        Droll       Dfix    GLD    TLT    XLV     SPY    VHT
0  2015-06-25 2015-06-24   4.24   0.00   0.00    0.00  95.76
1  2015-09-25 2015-09-24  18.61   8.43   0.00   16.81  56.15
2  2015-12-28 2015-12-24   0.00  23.08   7.91   69.01   0.00
3  2016-03-28 2016-03-24   0.00  59.80  33.24    6.96   0.00
4  2016-06-27 2016-06-24   0.00  88.11   0.00   11.89   0.00
5  2016-09-27 2016-09-26  10.12  89.88   0.00    0.00   0.00
6  2016-12-27 2016-12-23  43.55   0.00   0.00   56.45   0.00
7  2017-03-28 2017-03-27   0.00   0.00   0.00  100.00   0.00
8  2017-06-27 2017-06-26   0.00   0.00   0.00  100.00   0.00
9  2017-09-26 2017-09-25   0.00   0.00   0.00  100.00   0.00
10 2017-12-26 2017-12-22   0.00   0.00   0.00   29.68  70.32
11 2018-03-26 2018-03-23   8.16   0.00   0.00   53.83  38.01
12 2018-06-26 2018-06-25  26.92   5.81   0.00   60.28   6.99
13 2018-09-25 2018-09-24  19.04  15.69   0.00   50.66  14.61
14 2018-12-26 2018-12-24  35.59   0.00   0.00    0.00  64.41
15 2019-03-26 2019-03-25  10.11  38.31  51.58    0.00   0.00
16 2019-06-25 2019-06-24   0.00  49.71  50.29    0.00   0.00
17 2019-09-25 2019-09-24  43.59  24.00  32.41    0.00   0.00
18 2019-12-26 2019-12-24   0.00  67.68   0.87   31.45   0.00
19 2020-03-26 2020-03-25   0.00  75.97   0.00   24.03   0.00
20 2020-06-25 2020-06-24  34.49  46.62  15.55    0.00   3.34
21 2020-09-25 2020-09-24  92.86   0.00   0.00    0.00   7.14
22 2020-12-28 2020-12-24  79.54   0.27   0.00    0.00  20.18
23 2021-03-26 2021-03-25   3.12  21.18   0.00    0.00  75.71
24 2021-06-25 2021-06-24   0.00   0.00   0.00  100.00   0.00
25 2021-09-27 2021-09-24   0.00   0.00   0.00  100.00   0.00
26 2021-12-28 2021-12-27   0.00   0.00   0.00  100.00   0.00
27 2022-03-28 2022-03-25  18.05   0.00  27.05   54.91   0.00
28 2022-06-27 2022-06-24  11.75   0.00  88.25    0.00   0.00
29 2022-09-27 2022-09-26   1.95   0.00  98.05    0.00   0.00
30 2022-12-27 2022-12-23  19.72   8.65  64.44    0.00   7.19
31 2023-03-28 2023-03-27  44.86   0.00  55.14    0.00   0.00
32 2023-06-27 2023-06-26  49.44   0.00   3.92    0.00  46.64
33 2023-09-26 2023-09-25  38.01   0.00  15.53   46.47   0.00
34 2023-12-26 2023-12-22  32.79   0.00   0.00   67.21   0.00
35 2024-03-25 2024-03-22  24.12   0.00   0.00   75.88   0.00
36 2024-06-25 2024-06-24  18.39   0.00   0.00   81.61   0.00
37 2024-09-25 2024-09-24  89.95   0.00   0.00   10.05   0.00
38 2024-12-26 2024-12-24  77.39   0.00   0.00   22.61   0.00
39 2025-03-26 2025-03-25  62.74   0.00   0.00   37.26   0.00
40 2025-06-25 2025-06-24  75.04   0.00   0.00   24.96   0.00
41 2025-09-25 2025-09-24  68.18   0.00   0.00   31.82   0.00
42 2025-12-26 2025-12-24  69.05   0.00   0.00   30.95   0.00
43 2026-03-26 2026-03-25  67.24   0.00   0.00   32.76   0.00
44 2026-06-25 2026-06-24    NaN    NaN    NaN     NaN    NaN