# Naive portfolio strategies - comparisons

The following "naive" portfolios are considered:

- equal weighted portfolio (on the rebalancing date, the weights are proportional to 1/N, where N is the number of portfolio components).
- inverse volatility (on the rebalancing date, the weights are proportional to the inverse of the portfolio component volatilities, experienced during a predefined historical lookback period).
- inverse variance (on the rebalancing date, the weights are proportional to the inverse of the portfolio component variances, experienced during a predefined historical lookback period).
- inverse drawdown (on the rebalancing date, the weights are proportional to the asset maximum historical drawdwon, observed over a predefined historical lookback period).

We start by importing the **azapy** and other useful packages.

In [1]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0", flush=True)

azapy version 1.2.5 >= 1.2.0

### Collect historical market data

Note the flag `force=False`. In this case the function will attempt to read the market data from `mktdir`. If it fails, then it will access the data provider servers, in this case *yahoo*. For more information see https://azapy.readthedocs.io/en/latest/.

In [2]:
symb = ['GLD', 'TLT', 'XLV', 'VGT', 'VHT']

sdate = "2012-01-01"
edate = "2021-07-27"

mktdir = "../MkTdata"

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

read GLD data from file
read TLT data from file
read XLV data from file
read VGT data from file
read VHT data from file

Request between 2012-01-03 : 2021-07-27
                    GLD         TLT         XLV         VGT         VHT
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               2407        2407        2407        2407        2407
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2021-07-27  2021-07-27  2021-07-27  2021-07-27  2021-07-27
error                No          No          No          No          No
extraction time 0.161 s

### Set the model parameters

Since we are interested to run several portfolio strategies, it is convenient to setup the model parameters in a dictionary. 
The keys are given by the portfolio names while the model parameters are encapsulated in a dictionary:

- `type` is the name of the portfolio class, 
- `m_param` is a dictionary of parameters to be set by `set_model` method.

The `hlength`is set to 3.25 years. This is the length of historical lookback period used to calibrate the historical volatilities, variances and maximum drawdowns.

For `P_N`, the `ww` is set to `None`, indicating the default setup for equal weighted portfolio. 

*For more details see the documentations for Port_InvVol, Port_InvVar, Port_InvDD and Port_ConstW classes.*

In [3]:
models = {'P_InvVol': {'type': 'Port_InvVol', 'm_param': {'hlength': 3.25}},
          'P_InvVaR': {'type': 'Port_InvVar', 'm_param': {'hlength': 3.25}},
          'P_InvDD': {'type': 'Port_InvDD', 'm_param': {'hlength': 3.25}},
          'P_N': {'type': 'Port_ConstW', 'm_param': {'ww': None}}}

### Main computational loop

- `port` is the list of portfolio time-series.
- `pp` is a list of portfolio objects. They could be interrogated later for specific information.

In [4]:
port = []
pp = {}
for key, val in models.items():
    ppz = getattr(az, val['type'])
    pp_ = ppz(mktdata, pname=key)
    pp[key] = pp_
    port_ = pp_.set_model(**val['m_param'])
    port.append(port_)

### Prepare the results for comparisons 

Build a `Port_Simple` class holding all the computed portfolios as components. We use this structure to build comparative graphical and numerical performance reports. The aggregated portfolio of portfolios time-series will be neglected.

>Note the call to `set_model` method that is a must.

>Observation: `Port_Simple` is the class that supports the back testing of "Buy and Hold" portfolio (_see its documentation_).
It also can be used as a tool to compare the performance of multiple portfolios. Here we use it in this latter capacity.

In [5]:
ps = az.Port_Simple(port, col='close', pname='ALL')
_ = ps.set_model()

### Visualize the portfolio time-series

Note the use of the flags
- `componly=True` to retain only the original portfolios time-series and to exclude the aggregated portfolio of portfolios time-series,
- `fancy=True` to use the `plotly` interactive time series package.

*For more details see the documentation.*

In [6]:
_ = ps.port_view_all(componly=True, fancy=True, title="Relative performance")

### Portfolio performances 

We are using the same flags as above.

In this case the `P_InvDD` is the best performer. It also has the highest beta with higher rate of returns and smaller maximum drawdown than the equal weighted portfolio.

In [7]:
ps.port_perf(componly=True, fancy=True)

             RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
P_InvDD   13.35 -15.69  0.851128  2020-03-20  2020-02-19  2020-04-09       50
P_N       13.32 -15.92  0.836395  2020-03-20  2020-02-19  2020-04-09       50
P_InvVol  12.54 -15.34  0.817765  2020-03-19  2020-02-19  2020-04-08       49
P_InvVaR  11.89 -14.94  0.795741  2020-03-19  2020-02-21  2020-04-08       47

### Portfolio annual returns

We are using the following flags:
- `withcom=True` to include the components in the report,
- `componly=True` to exclude the aggregated portfolio, 
- `fancy=True` to report the rates in percent.

The P_InvDD outperforms P_N almost every year. The exception is 2017 where the difference in the rate of returns is 25bps (bases points).

In [8]:
ps.port_annual_returns(withcomp=True, componly=True, fancy=True)

### Historical weights for P_InvDD

>Remark: At present the GLD weight is very small (less than 2%).

In [9]:
pp['P_InvDD'].get_weights(fancy=True)

        Droll       Dfix    GLD    TLT    XLV    VGT    VHT
0  2015-06-25 2015-06-24  11.38  15.69  28.67  17.67  26.60
1  2015-09-25 2015-09-24  14.28  13.16  26.51  19.64  26.41
2  2015-12-28 2015-12-24  12.55   2.85  35.23  15.12  34.26
3  2016-03-28 2016-03-24   9.56  15.04  26.84  22.44  26.11
4  2016-06-27 2016-06-24  10.91   5.83  29.48  25.60  28.19
5  2016-09-27 2016-09-26  19.75   5.25  26.55  23.06  25.39
6  2016-12-27 2016-12-23  17.80  20.36  21.89  19.01  20.93
7  2017-03-28 2017-03-27  14.62  21.58  23.20  18.42  22.18
8  2017-06-27 2017-06-26   9.32  22.92  24.64  19.56  23.56
9  2017-09-26 2017-09-25  17.75  21.28  22.88  16.20  21.88
10 2017-12-26 2017-12-22  17.71  21.23  22.82  16.42  21.82
11 2018-03-26 2018-03-23  12.51  19.92  21.71  22.48  23.38
12 2018-06-26 2018-06-25  23.18  24.99  19.28  12.67  19.87
13 2018-09-25 2018-09-24  20.69  22.30  24.29   9.97  22.76
14 2018-12-26 2018-12-24  24.47  14.36  22.35  18.62  20.20
15 2019-03-26 2019-03-25  22.03  18.09  20.87  18.71  20.30
16 2019-06-25 2019-06-24  21.04  20.51  21.85  13.90  22.71
17 2019-09-25 2019-09-24  17.12  13.37  20.41  25.58  23.52
18 2019-12-26 2019-12-24  23.35  18.20  21.78  17.00  19.67
19 2020-03-26 2020-03-25  24.05  22.89  17.67  17.50  17.89
20 2020-06-25 2020-06-24   4.89  26.89  22.72  22.51  23.00
21 2020-09-25 2020-09-24  22.08  14.22  21.21  21.01  21.47
22 2020-12-28 2020-12-24  22.13  14.26  21.26  20.83  21.52
23 2021-03-26 2021-03-25  25.56   7.87  17.66  24.06  24.85
24 2021-06-25 2021-06-24   1.81  24.63  24.59  24.09  24.89
25 2021-09-27 2021-09-24    NaN    NaN    NaN    NaN    NaN