# Naive portfolio strategies - comparisons

The following "naive" portfolios are considered:

- equal weighted portfolio (on the rebalancing date, the weights are proportional to 1/N, where N is the number of portfolio components).
- inverse volatility (on the rebalancing date, the weights are proportional to the inverse of the portfolio component volatilities, experienced during a predefined historical lookback period).
- inverse variance (on the rebalancing date, the weights are proportional to the inverse of the portfolio component variances, experienced during a predefined historical lookback period).
- inverse drawdown (on the rebalancing date, the weights are proportional to the asset maximum historical drawdwon, observed over a predefined historical lookback period).

We start by importing the **azapy** and other useful packages.

In [10]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0", flush=True)

azapy version 1.2.6 >= 1.2.0

### Collect historical market data

Note the flag `force=False`. In this case the function will attempt to read the market data from `mktdir`. If it fails, then it will access the data provider servers, in this case *yahoo*. For more information see https://azapy.readthedocs.io/en/latest/.

In [11]:
symb = ['GLD', 'TLT', 'XLV', 'SPY', 'VHT']

sdate = "2012-01-01"
edate = "today"

mktdir = "../MkTdata"

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

read GLD data from file
read TLT data from file
read XLV data from file
read SPY data from file
read VHT data from file

Request between 2012-01-03 : 2026-05-05
                    GLD         TLT         XLV         SPY         VHT
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3605        3605        3605        3605        3605
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error                No          No          No          No          No
extraction time 0.268 s

### Set the model parameters

Since we are interested to run several portfolio strategies, it is convenient to setup the model parameters in a dictionary. 
The keys are given by the portfolio names while the model parameters are encapsulated in a dictionary:

- `type` is the name of the portfolio class, 
- `m_param` is a dictionary of parameters to be set by `set_model` method.

The `hlength`is set to 3.25 years. This is the length of historical lookback period used to calibrate the historical volatilities, variances and maximum drawdowns.

For `P_N`, the `ww` is set to `None`, indicating the default setup for equal weighted portfolio. 

*For more details see the documentations for Port_InvVol, Port_InvVar, Port_InvDD and Port_ConstW classes.*

In [12]:
models = {'P_InvVol': {'type': 'Port_InvVol', 'm_param': {'hlength': 3.25}},
          'P_InvVaR': {'type': 'Port_InvVar', 'm_param': {'hlength': 3.25}},
          'P_InvDD': {'type': 'Port_InvDD', 'm_param': {'hlength': 3.25}},
          'P_N': {'type': 'Port_ConstW', 'm_param': {'ww': None}}}

### Main computational loop

- `port` is the list of portfolio time-series.
- `pp` is a list of portfolio objects. They could be interrogated later for specific information.

In [13]:
port = []
pp = {}
for key, val in models.items():
    ppz = getattr(az, val['type'])
    pp_ = ppz(mktdata, pname=key)
    pp[key] = pp_
    port_ = pp_.set_model(**val['m_param'])
    port.append(port_)

### Prepare the results for comparisons 

Build a `Port_Simple` class holding all the computed portfolios as components. We use this structure to build comparative graphical and numerical performance reports. The aggregated portfolio of portfolios time-series will be neglected.

>Note the call to `set_model` method that is a must.

>Observation: `Port_Simple` is the class that supports the back testing of "Buy and Hold" portfolio (_see its documentation_).
It also can be used as a tool to compare the performance of multiple portfolios. Here we use it in this latter capacity.

In [14]:
ps = az.Port_Simple(port, col='close', pname='ALL')
_ = ps.set_model()

### Visualize the portfolio time-series

Note the use of the flags
- `componly=True` to retain only the original portfolios time-series and to exclude the aggregated portfolio of portfolios time-series,
- `fancy=True` to use the `plotly` interactive time series package.

*For more details see the documentation.*

In [15]:
_ = ps.port_view_all(componly=True, fancy=True, title="Relative performance")

### Portfolio performances 

We are using the same flags as above.

In this case the `P_InvDD` is the best performer. It also has the highest beta with higher rate of returns and smaller maximum drawdown than the equal weighted portfolio.

In [16]:
ps.port_perf(componly=True, fancy=True)

            RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
P_InvVaR  8.54 -17.78  0.480322  2022-10-20  2021-12-30  2024-02-01      763
P_InvVol  8.72 -18.55  0.469966  2022-10-20  2021-12-30  2024-02-22      784
P_N       8.93 -19.16  0.466181  2022-10-20  2021-12-30  2024-02-23      785
P_InvDD   9.22 -21.17  0.435375  2022-10-20  2021-12-31  2024-02-22      783

### Portfolio annual returns

We are using the following flags:
- `withcom=True` to include the components in the report,
- `componly=True` to exclude the aggregated portfolio, 
- `fancy=True` to report the rates in percent.

The P_InvDD outperforms P_N almost every year. The exception is 2017 where the difference in the rate of returns is 25bps (bases points).

In [17]:
ps.port_annual_returns(withcomp=True, componly=True, fancy=True)

### Historical weights for P_InvDD

>Remark: At present the GLD weight is very small (less than 2%).

In [18]:
pp['P_InvDD'].get_weights(fancy=True)

        Droll       Dfix    GLD    TLT    XLV    SPY    VHT
0  2015-06-25 2015-06-24  13.12  18.10  33.06   5.04  30.68
1  2015-09-25 2015-09-24  14.02  12.92  26.03  21.10  25.93
2  2015-12-28 2015-12-24  10.71   2.43  30.08  27.53  29.25
3  2016-03-28 2016-03-24   9.49  14.92  26.63  23.05  25.90
4  2016-06-27 2016-06-24  10.89   5.82  29.44  25.71  28.14
5  2016-09-27 2016-09-26  19.72   5.24  26.52  23.16  25.35
6  2016-12-27 2016-12-23  17.78  20.34  21.87  19.10  20.91
7  2017-03-28 2017-03-27  14.65  21.62  23.25  18.25  22.23
8  2017-06-27 2017-06-26   9.34  22.97  24.70  19.38  23.61
9  2017-09-26 2017-09-25  19.14  22.95  24.68   9.63  23.60
10 2017-12-26 2017-12-22  17.55  21.04  22.62  17.17  21.63
11 2018-03-26 2018-03-23  12.77  20.35  22.17  20.84  23.87
12 2018-06-26 2018-06-25  23.82  25.67  19.81  10.28  20.42
13 2018-09-25 2018-09-24  19.69  21.22  23.11  14.32  21.66
14 2018-12-26 2018-12-24  24.51  14.38  22.39  18.49  20.23
15 2019-03-26 2019-03-25  22.07  18.11  20.90  18.59  20.33
16 2019-06-25 2019-06-24  19.79  19.29  20.55  19.00  21.36
17 2019-09-25 2019-09-24  17.33  13.54  20.66  24.65  23.81
18 2019-12-26 2019-12-24  23.29  18.15  21.72  17.22  19.62
19 2020-03-26 2020-03-25  24.01  22.86  17.64  17.63  17.86
20 2020-06-25 2020-06-24   4.88  26.84  22.67  22.65  22.95
21 2020-09-25 2020-09-24  22.04  14.20  21.17  21.15  21.43
22 2020-12-28 2020-12-24  22.04  14.20  21.17  21.15  21.43
23 2021-03-26 2021-03-25  27.07   8.33  18.70  19.59  26.32
24 2021-06-25 2021-06-24   1.91  26.08  26.04  19.62  26.36
25 2021-09-27 2021-09-24   1.68  35.21  22.87  17.09  23.15
26 2021-12-28 2021-12-27  26.29  24.93  16.20  16.18  16.40
27 2022-03-28 2022-03-25  13.41  29.64  19.26  18.19  19.49
28 2022-06-27 2022-06-24  27.82  24.47  17.14  13.23  17.35
29 2022-09-27 2022-09-26  30.47  30.01  21.01  16.23   2.28
30 2022-12-27 2022-12-23  28.00  19.49  18.86  14.56  19.09
31 2023-03-28 2023-03-27  29.28  26.27   3.44  34.28   6.73
32 2023-06-27 2023-06-26  22.24   7.22  23.45  23.16  23.92
33 2023-09-26 2023-09-25  18.74   3.97  26.02  24.02  27.25
34 2023-12-26 2023-12-22   8.03  12.29  26.83  24.76  28.09
35 2024-03-25 2024-03-22  21.79  11.67  23.74  20.26  22.53
36 2024-06-25 2024-06-24  21.10  15.08  23.19  18.63  22.00
37 2024-09-25 2024-09-24   8.25  14.04  29.33  24.34  24.04
38 2024-12-26 2024-12-24  26.46   8.13  24.69  20.49  20.23
39 2025-03-26 2025-03-25  39.89  18.84   8.50   1.09  31.67
40 2025-06-25 2025-06-24  28.25  10.29  28.40   2.32  30.74
41 2025-09-25 2025-09-24  30.18  22.10  15.50  12.62  19.60
42 2025-12-26 2025-12-24  31.11   1.68  22.62  22.31  22.28
43 2026-03-26 2026-03-25  32.11  15.48  23.71  27.87   0.84
44 2026-06-25 2026-06-24    NaN    NaN    NaN    NaN    NaN