# Sharpe optimal portfolio - comparisons

This example compares the performance of several risk-Sharpe optimal portfolios. 

The CVaR, SMCR, EVaR, MAD, LSD, BTAD, BTSD, GINI, SD and MV risk-based portfolios are considered. We use the `rtype=Sharpe` optimization flag with a risk-free rate of 0 (default value).

We start by importing **azapy** and other useful packages.

In [1]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0")

azapy version 1.2.6 >= 1.2.0

### Collect historical market data

- `symb` is the list of stock symbols (portfolio components).
- `sdate` and `edate` are the start and end dates of historical time-series.
- `force=True` get historical market data directly from the provider (in this case yahoo)
- `save=False` the historical market data is not saved

>For more information see https://azapy.readthedocs.io/en/latest/.

In [2]:
symb = ['GLD', 'TLT', 'XLV', 'SPY', 'VHT']

sdate = "2012-01-01"
edate = "today"

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, force=True, save=False)

get GLD from yahoo only
get TLT from yahoo only
get XLV from yahoo only
get SPY from yahoo only
get VHT from yahoo only

Request between 2012-01-03 : 2026-05-05
                    GLD         TLT         XLV         SPY         VHT
source            yahoo       yahoo       yahoo       yahoo       yahoo
force              True        True        True        True        True
save              False       False       False       False       False
file_dir         outDir      outDir      outDir      outDir      outDir
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3605        3605        3605        3605        3605
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error                No          No          No          No          No
extraction time 1.9 s

### Set scenarios model parameters

Since we plan to run many scenarios, it is useful to organize their model parameters in a dictionary.
The keys are the portfolio names, and the values are the model parameters organized also as dictionaries:
- 'type' : is the portfolio class used in the simulation,
- 'm_param' : is a dictionary with parameters for `set_model` functions.

Note that:
- `'P_N'` is the reference equal weighted portfolio,
- `'P_CVaR'` is the mCVaR optimal portfolio with confidence levels `alpha_CVaR` equal weighted,
- `'P_SMCR'` is the mSMCR optimal portfolio with confidence levels `alpha_SMCR` equal weighted,
- `'P_EVaR'` is the mEVaR optimal portfolio with confidence levels `alpha_EVaR` equal weighted.
- `'P_MAD'` is the mMAD optimal portfolio with weights `coef_MAD`,
- `'P_LSD'` is the mLSD optimal portfolio with weights `coef_LSD`,
- `'P_Omega'` is the mBTAD optimal portfolio with threshold levels `alpha_BTAD` equal weighted,
- `'P_Sortino'` is the mBTSD optimal portfolio with threshold levels `alpha_BTSD` equal weighted,
- `'P_GINI'` is the Gini optimal portfolio (commented out in `models` dictionary below, for speed reasons),
- `'P_MV'` is the MV optimal portfolio,
- `'P_SD'` is the SD optimal portfolio.


- In all cases the optimization type is set to `rtype='Sharpe'` (optimal portfolio with the same risk profile as the equal weighted portfolio) with risk-free rate mu0=0.
- The `'hlength'` parameter (the length of historical data used in weights calibration) is set to 3.25 years except for `'P_GINI'` where it is set to 1.25 years (for computational speed convenience).

> Note:
> - mBTAD-Sharpe ratio is called Omega ratio 
> - mBTSD-Sharpe ratio is called Sortino ratio 
> - MV-Sharpe ratio is different than (SD) Sharp ratio

In [3]:
rtype = 'Sharpe'
alpha_CVaR = [0.95, 0.90, 0.85]
alpha_SMCR = [0.9, 0.80]
coef_MAD = [1./3.] * 3
coef_LSD = [1./3.] * 3
alpha_BTAD = [-0.01, 0]
alpha_BTSD = [-0.01, 0]
alpha_EVaR = [0.75, 0.65]
hlength = 1.25

models = {'P_CVaR-Sharpe': {'type': 'Port_CVaR', 'm_param': {'alpha': alpha_CVaR, 'rtype': rtype, 'hlength': hlength}},
          'P_SMCR-Sharpe': {'type': 'Port_SMCR', 'm_param': {'alpha': alpha_SMCR, 'rtype': rtype, 'hlength': hlength}},
          'P_EVaR-Sharpe': {'type': 'Port_EVaR', 'm_param': {'alpha': alpha_EVaR, 'rtype': rtype, 'hlength': hlength}},
          'P_MAD-Sharpe': {'type': 'Port_MAD', 'm_param': {'coef': coef_MAD, 'rtype': rtype, 'hlength': hlength}},
          'P_LSD-Sharpe': {'type': 'Port_LSD', 'm_param': {'coef': coef_LSD, 'rtype': rtype, 'hlength': hlength}},
          'P_Omega': {'type': 'Port_BTAD', 'm_param': {'alpha': alpha_BTAD, 'rtype': rtype, 'hlength': hlength}},
          'P_Sortino': {'type': 'Port_BTSD', 'm_param': {'alpha': alpha_BTSD, 'rtype': rtype, 'hlength': hlength}},
          #'P_GINI-Sharpe': {'type': 'Port_GINI', 'm_param': {'rtype': rtype, 'hlength': 1.25}},
          'P_MV-Sharpe': {'type': 'Port_MV', 'm_param': {'rtype': rtype, 'hlength': hlength}},
          'P_Sharpe': {'type': 'Port_SD', 'm_param': {'rtype': rtype, 'hlength': hlength}},
          'P_N': {'type': 'Port_ConstW', 'm_param': {'ww': None}}}

### Main computation loop

- `port` is a list containing the simulated time-series. We will use it to setup a simple portfolio *(see the documentation for `Port_Simple` class)*. It is a very convenient way to facilitate the visual and numerical comparisons between these portfolio performances. 
- `pp` is a dictionary holding the portfolio objects. They may be used later for further analytical inquires.

In [4]:
port = []
pp = {}
for key, val in models.items():
    ppz = getattr(az, val['type'])
    pp_ = ppz(mktdata, pname=key)
    pp[key] = pp_
    port_ = pp_.set_model(**val['m_param'])
    port.append(port_)

### Prepare the results for comparisons 

Build a `Port_Simple` class holding all the computed portfolios as components. We use this structure to build comparative graphical and numerical performance reports. The aggregated portfolio of portfolios time-series will be neglected.

>Note the call to `set_model` method that is a must.

>Observation: `Port_Simple` is the class that supports the back testing of "Buy and Hold" portfolio (_see its documentation_).
It also can be used as a tool to compare the performance of multiple portfolios. Here we use it in this latter capacity.

In [5]:
ps = az.Port_Simple(port, col='close', pname='ALL')
_ = ps.set_model()

### Time-series visualization 

We used the flag `componly=True` to plot only the portfolio components.

In [6]:
_ = ps.port_view_all(componly=True, fancy=True, title="Relative performance")

### Portfolio performances

In [7]:
ps.port_perf(componly=True, fancy=True)

,RR,DD,RoMaD,DD_date,DD_start,DD_end,DD_days
symbol,,,,,,,
P_MAD-Sharpe,9.96,-20.14,0.494534,2022-09-30,2021-12-29,2024-03-08,800
P_Sharpe,9.91,-20.51,0.483264,2022-09-30,2021-12-29,2024-03-12,804
P_Omega,9.77,-20.82,0.469209,2022-09-30,2021-12-29,2024-03-20,812
P_N,8.95,-19.16,0.467048,2022-10-20,2021-12-30,2024-02-23,785
P_MV-Sharpe,9.55,-20.75,0.460382,2022-09-30,2021-12-29,2024-03-28,820
P_Sortino,9.46,-21.32,0.443680,2018-12-24,2018-01-26,2019-08-15,566
P_LSD-Sharpe,9.21,-21.44,0.429491,2018-12-24,2018-01-26,2019-08-15,566
P_EVaR-Sharpe,9.07,-21.25,0.426810,2018-12-24,2018-01-26,2019-08-27,578
P_SMCR-Sharpe,8.53,-20.32,0.419631,2018-12-24,2018-01-26,2019-08-15,566
P_CVaR-Sharpe,9.14,-22.18,0.412204,2018-12-24,2018-01-26,2019-08-28,579

### Annual returns

Note the best and worst performer each year.

> The flags `withcomp=True` includes the portfolios components while the flag `componly=True` excludes the aggregated portfolio of portfolios.

In [8]:
ps.port_annual_returns(withcomp=True, componly=True, fancy=True)

### Monthly returns

> Note: the flags `withcomp=True` includes the portfolios components while the flag `componly=True` excludes the aggregated portfolio.

In [9]:
ps.port_monthly_returns(withcomp=True, componly=True, fancy=True)

### A closer look at P_Omega portfolio

In [10]:
pp['P_Omega'].port_monthly_returns(fancy=True)

### P_Omega performance

An example of individual portfolio performance inquiry.

In [11]:
pp['P_Omega'].port_perf(fancy=True)

            RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
P_Omega   9.77 -20.82  0.469209  2022-09-30  2021-12-29  2024-03-20      812
SPY      14.89 -33.72  0.441738  2020-03-23  2020-02-19  2020-08-10      173
XLV      12.28 -28.40  0.432176  2020-03-23  2020-01-22  2020-07-15      175
VHT      12.40 -28.85  0.429692  2020-03-23  2020-02-19  2020-06-08      110
GLD       7.14 -42.11  0.169582  2015-12-17  2012-10-04  2020-07-22     2848
TLT       0.41 -48.35  0.008530  2023-10-19  2020-08-04         NaN     2100

### P_Omega drawdowns

In [12]:
pp['P_Omega'].port_drawdown(fancy=True)

       DD        Date       Start         End  NrDays
No
1  -20.82  2022-09-30  2021-12-29  2024-03-20     812
2  -19.75  2015-09-28  2015-07-20  2016-06-28     344
3  -18.97  2018-12-24  2018-09-20  2019-08-08     322
4  -16.85  2026-03-30  2026-01-29         NaN      96
5  -14.81  2020-03-18  2020-03-06  2020-04-08      33

### P_Omega weights

In [13]:
pp['P_Omega'].get_weights(fancy=True)

        Droll       Dfix    GLD     TLT     XLV     SPY    VHT
0  2015-06-25 2015-06-24   1.72    0.00    0.00    0.00  98.28
1  2015-09-25 2015-09-24   0.00    3.46    0.00    0.00  96.54
2  2015-12-28 2015-12-24   0.00   27.46   47.24   25.30   0.00
3  2016-03-28 2016-03-24   0.00  100.00    0.00    0.00   0.00
4  2016-06-27 2016-06-24   0.00   77.26    0.00   22.74   0.00
5  2016-09-27 2016-09-26   0.00   68.49    0.00   31.51   0.00
6  2016-12-27 2016-12-23  24.44    0.00    0.00   75.56   0.00
7  2017-03-28 2017-03-27   1.04    0.00    0.00   98.96   0.00
8  2017-06-27 2017-06-26   0.00    0.00    0.00  100.00   0.00
9  2017-09-26 2017-09-25   0.00    0.00    0.00  100.00   0.00
10 2017-12-26 2017-12-22   4.32   17.01    3.61   75.06   0.00
11 2018-03-26 2018-03-23  15.76    9.81    0.00   54.04  20.40
12 2018-06-26 2018-06-25  23.45    0.00    0.00   61.13  15.42
13 2018-09-25 2018-09-24   3.21    0.00    0.00   96.79   0.00
14 2018-12-26 2018-12-24  33.96    0.00    0.00    0.00  66.04
15 2019-03-26 2019-03-25  32.44   25.84   28.63    0.00  13.09
16 2019-06-25 2019-06-24  20.83   41.26   37.91    0.00   0.00
17 2019-09-25 2019-09-24  39.18   26.11   34.71    0.00   0.00
18 2019-12-26 2019-12-24   0.00   52.14   21.23   26.63   0.00
19 2020-03-26 2020-03-25   0.00   54.03   20.10   25.87   0.00
20 2020-06-25 2020-06-24   0.00   54.69   33.47   11.84   0.00
21 2020-09-25 2020-09-24   0.00   54.55   30.62   14.83   0.00
22 2020-12-28 2020-12-24   0.00   53.48    0.00   20.22  26.30
23 2021-03-26 2021-03-25   0.00   34.48    0.00    0.00  65.52
24 2021-06-25 2021-06-24   0.00    0.00   22.57   77.43   0.00
25 2021-09-27 2021-09-24   0.00    0.00   20.78   79.22   0.00
26 2021-12-28 2021-12-27   0.00    7.64    0.00   92.36   0.00
27 2022-03-28 2022-03-25  41.07    0.00   12.99   45.94   0.00
28 2022-06-27 2022-06-24  38.83    0.00   61.17    0.00   0.00
29 2022-09-27 2022-09-26   0.00    0.00  100.00    0.00   0.00
30 2022-12-27 2022-12-23   0.00    0.00  100.00    0.00   0.00
31 2023-03-28 2023-03-27  39.93    0.00   60.07    0.00   0.00
32 2023-06-27 2023-06-26  58.08    0.00    2.72    0.00  39.20
33 2023-09-26 2023-09-25  41.12    0.00    4.71   54.17   0.00
34 2023-12-26 2023-12-22  42.00    0.00    0.00   58.00   0.00
35 2024-03-25 2024-03-22  38.67    0.00    0.00   61.33   0.00
36 2024-06-25 2024-06-24  23.54    0.00    0.00   76.46   0.00
37 2024-09-25 2024-09-24  60.03    0.00    0.00   39.97   0.00
38 2024-12-26 2024-12-24  37.79    7.09    0.00   55.12   0.00
39 2025-03-26 2025-03-25  41.19    0.36    0.00   58.45   0.00
40 2025-06-25 2025-06-24  53.08    0.00    0.00   46.92   0.00
41 2025-09-25 2025-09-24  57.85    0.00    0.00   42.15   0.00
42 2025-12-26 2025-12-24  59.36    0.00    0.00   40.64   0.00
43 2026-03-26 2026-03-25  52.82    6.90    0.00   40.27   0.00
44 2026-06-25 2026-06-24    NaN     NaN     NaN     NaN    NaN