### This is an example of a portfolio of shares traded on other markets than USA. ###

We must make sure that the business calendar and the price time series are consistent with the exchange. 
Also any price/cash value is assumed to be denominated in the exchange currency. 

We use Stockholm exchange as an example.

In [1]:
import numpy as np
import azapy as az

print(f"azapy version {az.version()} >= 1.2.5")

azapy version 1.2.6 >= 1.2.5

Let's start by setting the exchange business calendar.

The Stockholm business calendar is abbreviated as "XSTO"

In [2]:
exch_calendar = 'XSTO'

Let's specify a set of (popular) shares traded on the Stockholm exchange.

Note the suffix .ST is specific to yahoo market data provider.

In [3]:
symb = ['GETI-B.ST', 'AZN.ST', 'SWED-A.ST', 'VOLV-B.ST', 'ASSA-B.ST', 'ELUX-B.ST']

Collect market data starting from 2012-01-01

In [4]:
sdate = "2012-01-01"
edate = "today"

mktdir = "../MkTdata"

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir, calendar=exch_calendar)

read GETI-B.ST data from file
get GETI-B.ST updates from yahoo
save GETI-B.ST updated data to file
read AZN.ST data from file
get AZN.ST updates from yahoo
save AZN.ST updated data to file
read SWED-A.ST data from file
get SWED-A.ST updates from yahoo
save SWED-A.ST updated data to file
read VOLV-B.ST data from file
get VOLV-B.ST updates from yahoo
save VOLV-B.ST updated data to file
read ASSA-B.ST data from file
get ASSA-B.ST updates from yahoo
save ASSA-B.ST updated data to file
read ELUX-B.ST data from file
get ELUX-B.ST updates from yahoo
save ELUX-B.ST updated data to file

Request between 2012-01-02 : 2026-05-05
              GETI-B.ST      AZN.ST   SWED-A.ST   VOLV-B.ST   ASSA-B.ST  \
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3593        3593        3593        3593        3593
sdate        2012-01-02  2012-01-02  2012-01-02  2012-01-02  2012-01-02
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error               Yes         Yes         Yes         Yes         Yes

              ELUX-B.ST
source            yahoo
force             False
save               True
file_dir     ../MkTdata
file_format         csv
api_key            None
nrow               3593
sdate        2012-01-02
edate        2026-05-05
error               Yes
extraction time 2.809 s

Note the value 'Yes' for the field 'error'. It means that collected market data has missing values. This could be a major concern for further computations.

Let's look more closely at the missing data. Instead of using the function `readMkT as above, we will use the class `MkTreader` to upload the historical data. 
This has the advantage of providing more info about the missing data.

In [5]:
mkt = az.MkTreader()
mktdata_ = mkt.get(symb, sdate=sdate, edate=edate, file_dir=mktdir, calendar=exch_calendar)

read GETI-B.ST data from file
read AZN.ST data from file
read SWED-A.ST data from file
read VOLV-B.ST data from file
read ASSA-B.ST data from file
read ELUX-B.ST data from file

Request between 2012-01-02 : 2026-05-05
              GETI-B.ST      AZN.ST   SWED-A.ST   VOLV-B.ST   ASSA-B.ST  \
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3593        3593        3593        3593        3593
sdate        2012-01-02  2012-01-02  2012-01-02  2012-01-02  2012-01-02
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error               Yes         Yes         Yes         Yes         Yes

              ELUX-B.ST
source            yahoo
force             False
save               True
file_dir     ../MkTdata
file_format         csv
api_key            None
nrow               3593
sdate        2012-01-02
edate        2026-05-05
error               Yes
extraction time 0.305 s

So far we have replicated the `readMkT` functionality; `mktdata` and `mktdata_` are identical.

However, the `mkt` object allows us to enquire about the nature of the errors.

In [6]:
mkt.get_error_log()

{'GETI-B.ST': {'mid': DatetimeIndex(['2013-05-10', '2019-06-10', '2019-06-17', '2019-08-05'], dtype='datetime64[us]', freq=None)},
 'AZN.ST': {'mid': DatetimeIndex(['2013-05-10', '2019-06-10', '2019-06-17', '2019-08-05'], dtype='datetime64[us]', freq=None)},
 'SWED-A.ST': {'mid': DatetimeIndex(['2013-05-10', '2019-06-10', '2019-06-17', '2019-08-05'], dtype='datetime64[us]', freq=None)},
 'VOLV-B.ST': {'mid': DatetimeIndex(['2013-05-10', '2019-06-10', '2019-06-17', '2019-08-05'], dtype='datetime64[us]', freq=None)},
 'ASSA-B.ST': {'mid': DatetimeIndex(['2013-05-10', '2019-06-10', '2019-06-17', '2019-08-05'], dtype='datetime64[us]', freq=None)},
 'ELUX-B.ST': {'mid': DatetimeIndex(['2013-05-10', '2019-06-10', '2019-06-17', '2019-08-05'], dtype='datetime64[us]', freq=None)}}

It appears that the missing data occurs in the middle of the time series, for the same 4 dates across all symbols ('2013-05-10', '2019-06-10', '2019-06-17', '2019-08-05').

Note, this behavior was recorded at the time when we were writing this script. In the future, yahoo may choose to correct these errors. 
In that case the next few lines of code involving data imputation may become superfluous. 

Since we are dealing with a very small number of missing data located well in the past and unrelated with any special market critical events, we can 
proceed to fill in the missing data using a linear imputation.

In [7]:
mktdata2 = mkt.set_imputation(method='linear')

`mktdata2` contain the same information as `mktdata` except that the missing data were replaced with interpolated values. 

It is easy to verify this by using the `summary_MkTdata` function

In [8]:
az.summary_MkTdata(mktdata2, calendar=exch_calendar)

      symbol      begin        end  length  na_total  na_b  na_e  cont
0  ASSA-B.ST 2012-01-02 2026-05-05    3597         0     0     0     0
1     AZN.ST 2012-01-02 2026-05-05    3597         0     0     0     0
2  ELUX-B.ST 2012-01-02 2026-05-05    3597         0     0     0     0
3  GETI-B.ST 2012-01-02 2026-05-05    3597         0     0     0     0
4  SWED-A.ST 2012-01-02 2026-05-05    3597         0     0     0     0
5  VOLV-B.ST 2012-01-02 2026-05-05    3597         0     0     0     0

Note the zero values in the last 4 columns.

For example the uncorrected market data, 'mktdata' from the original extraction (without imputation), returns

In [9]:
az.summary_MkTdata(mktdata, calendar=exch_calendar)

      symbol      begin        end  length  na_total  na_b  na_e  cont
0  ASSA-B.ST 2012-01-02 2026-05-05    3593         0     0     0     4
1     AZN.ST 2012-01-02 2026-05-05    3593         0     0     0     4
2  ELUX-B.ST 2012-01-02 2026-05-05    3593         0     0     0     4
3  GETI-B.ST 2012-01-02 2026-05-05    3593         0     0     0     4
4  SWED-A.ST 2012-01-02 2026-05-05    3593         0     0     0     4
5  VOLV-B.ST 2012-01-02 2026-05-05    3593         0     0     0     4

It signals (us we already know) the fact that 4 working dates, relative to the `exch_calendar` business calendar, are missing.

A faster way to compute the imputed market data is to use the `readMkT` with `imputation` value set.

In [10]:
mktdata2_ = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir, calendar=exch_calendar, imputation='linear')

read GETI-B.ST data from file
read AZN.ST data from file
read SWED-A.ST data from file
read VOLV-B.ST data from file
read ASSA-B.ST data from file
read ELUX-B.ST data from file

Request between 2012-01-02 : 2026-05-05
              GETI-B.ST      AZN.ST   SWED-A.ST   VOLV-B.ST   ASSA-B.ST  \
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3593        3593        3593        3593        3593
sdate        2012-01-02  2012-01-02  2012-01-02  2012-01-02  2012-01-02
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error               Yes         Yes         Yes         Yes         Yes

              ELUX-B.ST
source            yahoo
force             False
save               True
file_dir     ../MkTdata
file_format         csv
api_key            None
nrow               3593
sdate        2012-01-02
edate        2026-05-05
error               Yes
extraction time 0.311 s

mktdata2_ is identical to mktdata2. The missing data was filled using linear interpolation. 

Note:
1. The printed output (`verbose=True`) refers to the raw data (before imputation). Therefore, the field `error` is still `Yes`. This reminds us
that some of the market data was filled in. The `summary_MkTdata(mktdata2_, calendar=exch_calendar)` will summarize the corrected version of the market data. In general 
any imputation algorithm will introduce bias; therefore it is advisable to have a deep understanding of the nature of missing data and how it may influence future calculations.
If it is possible, it is always better to get the market data without omissions. In any event, before 
applying an imputation mechanism it is better to have a 
2. The saved market data (in `file_dir`) it always the raw (uncorrected) market data.

Further we will use `mktdata2` in our computations.

We will set a mixture CVaR risk measure and we will perform a backtesting for maximum Sharpe ratio optimal portfolio quarterly rebalanced. 

Note: The exchange calendar must be passed to the backtest simulator, in our case `Port_CVaR` object constructor.

In [11]:
alpha = [0.95, 0.90, 0.85]
coef = [1, 1, 1]

pr2 = az.Port_CVaR(mktdata2, pname='CVaRPort', capital=1000000, calendar=exch_calendar)
port2 = pr2.set_model(alpha=alpha, coef=coef, hlength=1.25)

The rest is the same as for any backtest analysis (e.g. see `OutOfSample_example.jpynb`). The monetary values should be understood to be denominated in the exchange currency. In our case 
is Swedish Krona.

In [12]:
_ = pr2.port_view(fancy=True, title="Portfolio performance")

In [13]:
_ = pr2.port_view_all(fancy=True, title="Relative performance")

In [14]:
pr2.get_weights()

,Droll,Dfix,ASSA-B.ST,AZN.ST,ELUX-B.ST,GETI-B.ST,SWED-A.ST,VOLV-B.ST
0,2015-06-25,2015-06-24,0.570651,0.000000,0.429349,0.000000,0.000000e+00,0.000000
1,2015-09-25,2015-09-24,0.756710,0.000000,0.243290,0.000000,0.000000e+00,0.000000
2,2015-12-23,2015-12-22,0.706352,0.000000,0.135443,0.158205,0.000000e+00,0.000000
3,2016-03-24,2016-03-23,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
4,2016-06-27,2016-06-23,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
5,2016-09-27,2016-09-26,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
6,2016-12-27,2016-12-23,0.246507,0.000000,0.000000,0.000000,0.000000e+00,0.753493
7,2017-03-28,2017-03-27,0.132503,0.034709,0.204455,0.000000,3.896136e-01,0.238720
8,2017-06-27,2017-06-26,0.128135,0.081097,0.094026,0.000000,5.595450e-01,0.137197
9,2017-09-26,2017-09-25,0.000000,0.000000,0.426531,0.000000,5.634383e-01,0.010030
10,2017-12-22,2017-12-21,0.000000,0.000000,0.504881,0.000000,9.045435e-02,0.404665
11,2018-03-26,2018-03-23,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000
12,2018-06-26,2018-06-25,0.000000,0.068556,0.000000,0.000000,0.000000e+00,0.931444
13,2018-09-25,2018-09-24,0.026918,0.731168,0.000000,0.000000,2.419140e-01,0.000000
14,2018-12-20,2018-12-19,0.169997,0.830003,0.000000,0.000000,0.000000e+00,0.000000
15,2019-03-26,2019-03-25,0.000000,0.713487,0.150933,0.000000,1.355797e-01,0.000000
16,2019-06-25,2019-06-24,0.000000,0.736027,0.137495,0.126477,0.000000e+00,0.000000
17,2019-09-25,2019-09-24,0.000000,0.681105,0.208852,0.110043,0.000000e+00,0.000000
18,2019-12-20,2019-12-19,0.000000,0.360580,0.444334,0.195086,0.000000e+00,0.000000
19,2020-03-26,2020-03-25,0.000000,0.355288,0.000000,0.644712,0.000000e+00,0.000000
20,2020-06-25,2020-06-24,0.000000,0.383383,0.000000,0.616617,0.000000e+00,0.000000
21,2020-09-25,2020-09-24,0.000000,0.331760,0.000000,0.668240,1.793031e-10,0.000000
22,2020-12-23,2020-12-22,0.000000,0.000000,0.000000,0.717181,0.000000e+00,0.282819
23,2021-03-26,2021-03-25,0.000000,0.000000,0.070433,0.715580,0.000000e+00,0.213987
24,2021-06-24,2021-06-23,0.000000,0.000000,0.106536,0.236341,0.000000e+00,0.657122
25,2021-09-27,2021-09-24,0.000000,0.000000,0.065283,0.162692,5.017139e-01,0.270311
26,2021-12-27,2021-12-23,0.000000,0.000000,0.000000,0.211211,5.477654e-01,0.241024
27,2022-03-28,2022-03-25,0.210387,0.577292,0.000000,0.068205,7.241018e-02,0.071706
28,2022-06-27,2022-06-23,0.134376,0.706940,0.000000,0.000000,1.286929e-01,0.029992
29,2022-09-27,2022-09-26,0.000000,0.770659,0.000000,0.000000,7.413425e-02,0.155206
30,2022-12-27,2022-12-23,0.000000,0.722522,0.000000,0.000000,2.774777e-01,0.000000
31,2023-03-28,2023-03-27,0.000000,0.528022,0.000000,0.000000,3.409723e-01,0.131006
32,2023-06-27,2023-06-26,0.000000,0.449447,0.000000,0.000000,3.109646e-01,0.239589
33,2023-09-26,2023-09-25,0.000000,0.168213,0.000000,0.000000,2.030561e-01,0.628731
34,2023-12-22,2023-12-21,0.000000,0.000000,0.000000,0.102230,4.257077e-02,0.855199
35,2024-03-25,2024-03-22,0.000000,0.000000,0.000000,0.086271,0.000000e+00,0.913729
36,2024-06-25,2024-06-24,0.369531,0.000000,0.000000,0.017973,5.656934e-01,0.046802
37,2024-09-25,2024-09-24,0.327225,0.274930,0.000000,0.168427,2.294174e-01,0.000000
38,2024-12-20,2024-12-19,0.850358,0.149642,0.000000,0.000000,0.000000e+00,0.000000
39,2025-03-26,2025-03-25,0.564688,0.061244,0.000000,0.000000,3.740672e-01,0.000000
40,2025-06-25,2025-06-24,0.129317,0.000000,0.000000,0.000000,8.706827e-01,0.000000
41,2025-09-25,2025-09-24,0.177765,0.000000,0.000000,0.000000,8.222345e-01,0.000000
42,2025-12-22,2025-12-19,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
43,2026-03-26,2026-03-25,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
44,2026-06-25,2026-06-24,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
pr2.port_perf(fancy=True)

              RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
CVaRPort   13.11 -34.30  0.382143  2025-04-07  2024-03-27  2025-12-11      624
AZN.ST     13.38 -29.95  0.446848  2025-04-09  2024-08-29  2025-11-25      453
ASSA-B.ST  15.47 -35.35  0.437578  2020-03-23  2020-02-20  2021-03-25      399
SWED-A.ST  16.62 -49.11  0.338420  2020-05-14  2018-09-27  2021-10-21     1120
VOLV-B.ST  14.65 -43.81  0.334505  2020-03-18  2020-02-20  2020-09-28      221
GETI-B.ST   4.98 -59.53  0.083623  2024-11-21  2021-11-15         NaN     1632
ELUX-B.ST   0.10 -79.09  0.001207  2026-04-24  2021-03-25         NaN     1867

In [16]:
pr2.port_drawdown(fancy=True)

       DD        Date       Start         End  NrDays
No
1  -34.30  2025-04-07  2024-03-27  2025-12-11     624
2  -30.66  2020-03-16  2020-01-17  2021-03-22     430
3  -24.18  2022-03-08  2021-11-17  2023-06-16     576
4  -22.71  2016-02-11  2015-11-30  2017-03-13     469
5  -19.31  2018-06-26  2017-10-03  2018-09-27     359

In [17]:
pr2.port_annual_returns(fancy=True)

In [18]:
pr2.port_monthly_returns(fancy=True)

In [19]:
pr2.port_period_returns(fancy=True)

,Droll,Dfix,RR,ASSA-B.ST,AZN.ST,ELUX-B.ST,GETI-B.ST,SWED-A.ST,VOLV-B.ST
0,2015-06-25,2015-06-24,-9.15,57.07,0.00,42.93,0.00,0.00,0.00
1,2015-09-25,2015-09-24,12.30,75.67,0.00,24.33,0.00,0.00,0.00
2,2015-12-23,2015-12-22,-9.97,70.64,0.00,13.54,15.82,0.00,0.00
3,2016-03-24,2016-03-23,-1.17,100.00,0.00,0.00,0.00,0.00,0.00
4,2016-06-27,2016-06-23,4.70,100.00,0.00,0.00,0.00,0.00,0.00
5,2016-09-27,2016-09-26,3.97,100.00,0.00,0.00,0.00,0.00,0.00
6,2016-12-27,2016-12-23,18.15,24.65,0.00,0.00,0.00,0.00,75.35
7,2017-03-28,2017-03-27,6.29,13.25,3.47,20.45,0.00,38.96,23.87
8,2017-06-27,2017-06-26,5.30,12.81,8.11,9.40,0.00,55.95,13.72
9,2017-09-26,2017-09-25,-5.51,0.00,0.00,42.65,0.00,56.34,1.00
10,2017-12-22,2017-12-21,-6.92,0.00,0.00,50.49,0.00,9.05,40.47
11,2018-03-26,2018-03-23,-5.92,0.00,0.00,0.00,0.00,0.00,100.00
12,2018-06-26,2018-06-25,18.92,0.00,6.86,0.00,0.00,0.00,93.14
13,2018-09-25,2018-09-24,1.32,2.69,73.12,0.00,0.00,24.19,0.00
14,2018-12-20,2018-12-19,13.01,17.00,83.00,0.00,0.00,0.00,0.00
15,2019-03-26,2019-03-25,-3.83,0.00,71.35,15.09,0.00,13.56,0.00
16,2019-06-25,2019-06-24,10.56,0.00,73.60,13.75,12.65,0.00,0.00
17,2019-09-25,2019-09-24,8.70,0.00,68.11,20.89,11.00,0.00,0.00
18,2019-12-20,2019-12-19,-17.58,0.00,36.06,44.43,19.51,0.00,0.00
19,2020-03-26,2020-03-25,5.40,0.00,35.53,0.00,64.47,0.00,0.00
20,2020-06-25,2020-06-24,3.63,0.00,38.34,0.00,61.66,0.00,0.00
21,2020-09-25,2020-09-24,-5.20,0.00,33.18,0.00,66.82,0.00,0.00
22,2020-12-23,2020-12-22,21.99,0.00,0.00,0.00,71.72,0.00,28.28
23,2021-03-26,2021-03-25,25.11,0.00,0.00,7.04,71.56,0.00,21.40
24,2021-06-24,2021-06-23,-2.07,0.00,0.00,10.65,23.63,0.00,65.71
25,2021-09-27,2021-09-24,8.34,0.00,0.00,6.53,16.27,50.17,27.03
26,2021-12-27,2021-12-23,-9.98,0.00,0.00,0.00,21.12,54.78,24.10
27,2022-03-28,2022-03-25,-1.84,21.04,57.73,0.00,6.82,7.24,7.17
28,2022-06-27,2022-06-23,-4.23,13.44,70.69,0.00,0.00,12.87,3.00
29,2022-09-27,2022-09-26,14.25,0.00,77.07,0.00,0.00,7.41,15.52
30,2022-12-27,2022-12-23,-1.52,0.00,72.25,0.00,0.00,27.75,0.00
31,2023-03-28,2023-03-27,6.24,0.00,52.80,0.00,0.00,34.10,13.10
32,2023-06-27,2023-06-26,6.85,0.00,44.94,0.00,0.00,31.10,23.96
33,2023-09-26,2023-09-25,6.63,0.00,16.82,0.00,0.00,20.31,62.87
34,2023-12-22,2023-12-21,19.50,0.00,0.00,0.00,10.22,4.26,85.52
35,2024-03-25,2024-03-22,-14.93,0.00,0.00,0.00,8.63,0.00,91.37
36,2024-06-25,2024-06-24,9.07,36.95,0.00,0.00,1.80,56.57,4.68
37,2024-09-25,2024-09-24,-7.27,32.72,27.49,0.00,16.84,22.94,0.00
38,2024-12-20,2024-12-19,-5.81,85.04,14.96,0.00,0.00,0.00,0.00
39,2025-03-26,2025-03-25,-4.48,56.47,6.12,0.00,0.00,37.41,0.00
40,2025-06-25,2025-06-24,16.73,12.93,0.00,0.00,0.00,87.07,0.00
41,2025-09-25,2025-09-24,14.26,17.78,0.00,0.00,0.00,82.22,0.00
42,2025-12-22,2025-12-19,-3.18,0.00,0.00,0.00,0.00,100.00,0.00
43,2026-03-26,2026-03-25,17.30,0.00,0.00,0.00,0.00,100.00,0.00

In [20]:
pr2.get_nshares()

,ASSA-B.ST,AZN.ST,ELUX-B.ST,GETI-B.ST,SWED-A.ST,VOLV-B.ST,_CASH_
Droll,,,,,,,
2015-06-25,3551,0,1940,0,0,0,0
2015-09-25,4600,0,1199,0,0,0,0
2015-12-23,4077,0,822,1068,0,0,0
2016-03-24,5589,0,0,0,0,0,0
2016-06-27,5476,0,0,0,0,0,0
2016-09-27,5770,0,0,0,0,0,0
2016-12-27,1431,0,0,0,0,6933,0
2017-03-28,851,72,1215,0,2081,2144,0
2017-06-27,844,168,497,0,3465,1171,0
2017-09-26,0,0,2400,0,3378,86,0
2017-12-22,0,0,2766,0,545,3088,0
2018-03-26,0,0,0,0,0,7809,0
2018-06-26,0,125,0,0,0,7559,0
2018-09-25,193,1420,0,0,1448,0,0
2018-12-20,1349,1522,0,0,0,0,0
2019-03-26,0,1345,1117,0,1152,0,0
2019-06-25,0,1355,999,1228,0,0,0
2019-09-25,0,1214,1700,1194,0,0,0
2019-12-20,0,659,3934,1946,0,0,0
2020-03-26,0,594,0,5069,0,0,0
2020-06-25,0,561,0,5038,0,0,0
2020-09-25,0,509,0,5494,0,0,0
2020-12-23,0,0,0,5393,0,2049,0
2021-03-26,0,0,474,5277,0,1675,0
2021-06-24,0,0,1008,1665,0,6825,0
2021-09-27,0,0,700,947,6457,3080,0
2021-12-27,0,0,0,1296,7243,2764,0
2022-03-28,1750,983,0,398,976,844,0
2022-06-27,1296,1109,0,0,2016,391,0
2022-09-27,0,1222,0,0,962,1883,0
2022-12-27,0,1143,0,0,3512,0,0
2023-03-28,0,822,0,0,4465,1465,0
2023-06-27,0,709,0,0,4192,2721,0
2023-09-26,0,282,0,0,2542,6996,0
2023-12-22,0,0,0,1245,589,8988,0
2024-03-25,0,0,0,1336,0,9356,0
2024-06-25,3538,0,0,284,7383,491,0
2024-09-25,2913,533,0,2212,3186,0,0
2024-12-20,7320,295,0,0,0,0,0
2025-03-26,4885,109,0,0,3722,0,0
2025-06-25,1162,0,0,0,9202,0,0
2025-09-25,1627,0,0,0,8712,0,0
2025-12-22,0,0,0,0,10606,0,0
2026-03-26,0,0,0,0,11627,0,0

In [21]:
pr2.get_account(fancy=True)

,ASSA-B.ST,AZN.ST,ELUX-B.ST,GETI-B.ST,SWED-A.ST,VOLV-B.ST,_CASH_,cash_invst,cash_roll,cash_divd
Droll,,,,,,,,,,
2015-06-25,3551.0,0.0,1940.0,0.0,0.0,0.0,0.0,996780.22,3219.78,0.00
2015-09-25,4600.0,0.0,1199.0,0.0,0.0,0.0,0.0,924346.89,-15527.34,0.00
2015-12-23,4077.0,0.0,822.0,1068.0,0.0,0.0,0.0,1023887.06,-22463.91,0.00
2016-03-24,5589.0,0.0,0.0,0.0,0.0,0.0,0.0,873001.78,20065.62,0.00
2016-06-27,5476.0,0.0,0.0,0.0,0.0,0.0,0.0,886564.37,53171.17,14810.85
2016-09-27,5770.0,0.0,0.0,0.0,0.0,0.0,0.0,998210.00,2309.17,0.00
2016-12-27,1431.0,0.0,0.0,0.0,0.0,6933.0,0.0,993035.70,-5787.54,0.00
2017-03-28,851.0,72.0,1215.0,0.0,2081.0,2144.0,0.0,1164262.46,-6381.19,0.00
2017-06-27,844.0,168.0,497.0,0.0,3465.0,1171.0,0.0,1261978.80,5492.13,36990.20
2017-09-26,0.0,0.0,2400.0,0.0,3378.0,86.0,0.0,1316255.42,-6379.83,1979.50
2017-12-22,0.0,0.0,2766.0,0.0,545.0,3088.0,0.0,1219816.51,4393.71,0.00
2018-03-26,0.0,0.0,0.0,0.0,0.0,7809.0,0.0,1139333.05,17637.16,7085.00
2018-06-26,0.0,125.0,0.0,0.0,0.0,7559.0,0.0,1120529.50,7937.91,33188.25
2018-09-25,193.0,1420.0,0.0,0.0,1448.0,0.0,0.0,1314604.59,-25078.95,85.50
2018-12-20,1349.0,1522.0,0.0,0.0,0.0,0.0,0.0,1262272.16,11045.63,0.00
2019-03-26,0.0,1345.0,1117.0,0.0,1152.0,0.0,0.0,1487517.24,-6904.98,2234.30
2019-06-25,0.0,1355.0,999.0,1228.0,0.0,0.0,0.0,1419229.31,6112.24,21105.65
2019-09-25,0.0,1214.0,1700.0,1194.0,0.0,0.0,0.0,1564350.97,2871.98,974.24
2019-12-20,0.0,659.0,3934.0,1946.0,0.0,0.0,0.0,1726480.15,-20534.45,7225.00
2020-03-26,0.0,594.0,0.0,5069.0,0.0,0.0,0.0,1426195.03,-48000.12,964.78
2020-06-25,0.0,561.0,0.0,5038.0,0.0,0.0,0.0,1435193.12,-9907.62,0.00
2020-09-25,0.0,509.0,0.0,5494.0,0.0,0.0,0.0,1562930.19,-38114.57,7947.46
2020-12-23,0.0,0.0,0.0,5393.0,0.0,2049.0,0.0,1414469.21,-5275.10,0.00
2021-03-26,0.0,0.0,474.0,5277.0,0.0,1675.0,0.0,1769363.79,-9016.10,0.00
2021-06-24,0.0,0.0,1008.0,1665.0,0.0,6825.0,0.0,2256700.96,-25815.21,30906.00
2021-09-27,0.0,0.0,700.0,947.0,6457.0,3080.0,0.0,2225020.26,-22759.50,64837.50
2021-12-27,0.0,0.0,0.0,1296.0,7243.0,2764.0,0.0,2405904.15,-23090.69,61836.10
2022-03-28,1750.0,983.0,0.0,398.0,976.0,844.0,0.0,2120896.20,-34183.62,0.00
2022-06-27,1296.0,1109.0,0.0,0.0,2016.0,391.0,0.0,2108813.45,-59288.89,12705.00
2022-09-27,0.0,1222.0,0.0,0.0,962.0,1883.0,0.0,1931813.08,-6866.73,847.28
2022-12-27,0.0,1143.0,0.0,0.0,3512.0,0.0,0.0,2253505.50,5697.12,0.00
2023-03-28,0.0,822.0,0.0,0.0,4465.0,1465.0,0.0,2234278.53,4978.62,1860.80
2023-06-27,0.0,709.0,0.0,0.0,4192.0,2721.0,0.0,2419100.59,10530.57,53788.75
2023-09-26,0.0,282.0,0.0,0.0,2542.0,6996.0,0.0,2516383.96,27893.63,509.06
2023-12-22,0.0,0.0,0.0,1245.0,589.0,8988.0,0.0,2732050.65,-3023.30,0.00
2024-03-25,0.0,0.0,0.0,1336.0,0.0,9356.0,0.0,3229636.66,-4758.20,0.00
2024-06-25,3538.0,0.0,0.0,284.0,7383.0,491.0,0.0,2812741.25,32433.07,104116.40
2024-09-25,2913.0,533.0,0.0,2212.0,3186.0,0.0,0.0,3006892.16,20266.25,0.00
2024-12-20,7320.0,295.0,0.0,0.0,0.0,0.0,0.0,2807590.91,-2361.40,7865.10
2025-03-26,4885.0,109.0,0.0,0.0,3722.0,0.0,0.0,2568871.75,50710.54,6229.15
2025-06-25,1162.0,0.0,0.0,0.0,9202.0,0.0,0.0,2620605.42,23762.85,95178.15
2025-09-25,1627.0,0.0,0.0,0.0,8712.0,0.0,0.0,2928972.72,11196.86,0.00
2025-12-22,0.0,0.0,0.0,0.0,10606.0,0.0,0.0,3351496.00,-3295.49,4799.65
2026-03-26,0.0,0.0,0.0,0.0,11627.0,0.0,0.0,3536933.54,2175.09,316058.80