# Universal portfolio - Cover 1996

This is an example of how to evaluate a Universal portfolio. For more details see the library documentation 
https://azapy.readthedocs.io/en/latest/.

We start by importing **azapy** and other useful packages
(**azapy** version must be 1.2.1 or greater).

In [4]:
import azapy as az

print(f"azapy version {az.version()} >= 1.2.0")

azapy version 1.2.6 >= 1.2.0

### Collect historical market data

- `symb` is the list of stock symbols (portfolio components).
- `sdate` and `edate` are the start and end dates of historical time-series.
- `mktdir` is the name of the directory used as a buffer for market data collected from the data provider (in this case _alphavantage_).
    
> Note: if the flag `force=False` then a reading from `dir=mktdir` is attempted. If it fails, then the data provider servers will be accessed. The new data will be saved to the `dir=mktdir`. For more information see the readMkT documentation https://azapy.readthedocs.io/en/latest/.

In [5]:
mktdir = '../MkTdata'
sdate = '2012-01-01'
edate = 'today'
symb = ['VHT', 'SPY', 'XLV', 'GLD', 'ONEQ']

mktdata = az.readMkT(symb, sdate=sdate, edate=edate, file_dir=mktdir)

read VHT data from file
read SPY data from file
read XLV data from file
read GLD data from file
read ONEQ data from file

Request between 2012-01-03 : 2026-05-05
                    VHT         SPY         XLV         GLD        ONEQ
source            yahoo       yahoo       yahoo       yahoo       yahoo
force             False       False       False       False       False
save               True        True        True        True        True
file_dir     ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata  ../MkTdata
file_format         csv         csv         csv         csv         csv
api_key            None        None        None        None        None
nrow               3605        3605        3605        3605        3605
sdate        2012-01-03  2012-01-03  2012-01-03  2012-01-03  2012-01-03
edate        2026-05-05  2026-05-05  2026-05-05  2026-05-05  2026-05-05
error                No          No          No          No          No
extraction time 0.279 s

### Setup the Universal portfolio

First line is the constructor
Second line sets the model and execute the core computations. It is a Monte Carlo based evaluation.

- `mc_paths` - are the number of simulations per batch (must be >= 1)
- `nr_batches` - are the number of batches (must be >= 1). Note that the computation is multithreaded with one batch per thread.
- `variance_reduction = True` - default value (the MC will use the antithetic variance reduce implied by the permutations of the basket components)
- `alpha_dirichlet = None` - default value. In this case a uniform random generator of vectors in the M-simplex is used. This is equivalent to a Flat Dirichlet random generator (all alpha set to 1).

>Note the the total number of MC simulations is `mc_paths * nr_batches * M!` where `M` is the number of portfolio components and `M!` its factorial.

In [6]:
p4 = az.Port_Universal(mktdata, pname='UnivPort')    
port4 = p4.set_model(mc_paths=100, nr_batches=20, verbose=True)

nr simulations: 240000
simulation time: 0.225531

### Historical portfolio weights

>Note: if `_CASH_` is not an explicit component of the portfolio (it is not present in the `makdata`), then its weight is
set to `0`.
A `_CASH_` asset can be added to the `mktdata` by using the helper function `azapy.add_cash_security(mktdata)`.

In [7]:
p4.get_weights()

,Droll,Dfix,GLD,ONEQ,SPY,VHT,XLV,_CASH_
0,2015-06-25,2015-06-24,0.200000,0.200000,0.200000,0.200000,0.200000,0
1,2015-09-25,2015-09-24,0.201855,0.199825,0.199666,0.199324,0.199328,0
2,2015-12-28,2015-12-24,0.198453,0.200917,0.200887,0.199667,0.200076,0
3,2016-03-28,2016-03-24,0.203406,0.199633,0.201226,0.197359,0.198375,0
4,2016-06-27,2016-06-24,0.205168,0.198450,0.200392,0.197561,0.198430,0
5,2016-09-27,2016-09-26,0.203634,0.200263,0.200429,0.197612,0.198061,0
6,2016-12-27,2016-12-23,0.199020,0.202654,0.203369,0.197230,0.197726,0
7,2017-03-28,2017-03-27,0.200035,0.202541,0.202225,0.197429,0.197770,0
8,2017-06-27,2017-06-26,0.197942,0.203043,0.201925,0.198445,0.198645,0
9,2017-09-26,2017-09-25,0.198769,0.202867,0.201984,0.198092,0.198288,0
10,2017-12-26,2017-12-22,0.196569,0.204716,0.203321,0.197629,0.197764,0
11,2018-03-26,2018-03-23,0.198592,0.205096,0.202438,0.197091,0.196782,0
12,2018-06-26,2018-06-25,0.195333,0.206399,0.202887,0.198004,0.197376,0
13,2018-09-25,2018-09-24,0.191667,0.206255,0.203257,0.199601,0.199221,0
14,2018-12-26,2018-12-24,0.198648,0.202715,0.201071,0.198585,0.198980,0
15,2019-03-26,2019-03-25,0.195510,0.205247,0.202456,0.198473,0.198315,0
16,2019-06-25,2019-06-24,0.196204,0.205439,0.202711,0.197833,0.197813,0
17,2019-09-25,2019-09-24,0.198471,0.205169,0.202837,0.196768,0.196756,0
18,2019-12-26,2019-12-24,0.194904,0.206059,0.202701,0.198226,0.198111,0
19,2020-03-26,2020-03-25,0.203214,0.205095,0.199538,0.196026,0.196127,0
20,2020-06-25,2020-06-24,0.199609,0.208519,0.199893,0.196366,0.195613,0
21,2020-09-25,2020-09-24,0.199599,0.209277,0.200221,0.195796,0.195107,0
22,2020-12-28,2020-12-24,0.196144,0.211896,0.200955,0.196395,0.194610,0
23,2021-03-26,2021-03-25,0.193238,0.212006,0.202704,0.196606,0.195445,0
24,2021-06-25,2021-06-24,0.191513,0.212899,0.202981,0.196922,0.195686,0
25,2021-09-27,2021-09-24,0.189882,0.213258,0.203300,0.197234,0.196327,0
26,2021-12-28,2021-12-27,0.189262,0.213318,0.203966,0.196752,0.196701,0
27,2022-03-28,2022-03-25,0.192768,0.210590,0.203469,0.196276,0.196897,0
28,2022-06-27,2022-06-24,0.193870,0.207390,0.202102,0.197872,0.198766,0
29,2022-09-27,2022-09-26,0.192470,0.207577,0.202381,0.198287,0.199284,0
30,2022-12-27,2022-12-23,0.193431,0.204241,0.201835,0.199605,0.200888,0
31,2023-03-28,2023-03-27,0.195250,0.207490,0.202194,0.197020,0.198047,0
32,2023-06-27,2023-06-26,0.192942,0.210216,0.203334,0.196281,0.197228,0
33,2023-09-26,2023-09-25,0.192863,0.210266,0.203591,0.195948,0.197332,0
34,2023-12-26,2023-12-22,0.192610,0.212164,0.204262,0.194949,0.196015,0
35,2024-03-25,2024-03-22,0.191769,0.212642,0.204968,0.194636,0.195986,0
36,2024-06-25,2024-06-24,0.192738,0.213507,0.204999,0.193658,0.195098,0
37,2024-09-25,2024-09-24,0.194941,0.212398,0.204658,0.193351,0.194652,0
38,2024-12-26,2024-12-24,0.194387,0.216545,0.206686,0.190649,0.191734,0
39,2025-03-26,2025-03-25,0.198686,0.212667,0.204730,0.191230,0.192688,0
40,2025-06-25,2025-06-24,0.201080,0.215023,0.205831,0.188471,0.189594,0
41,2025-09-25,2025-09-24,0.202228,0.216712,0.206094,0.187082,0.187884,0
42,2025-12-26,2025-12-24,0.204814,0.214509,0.203943,0.187980,0.188754,0
43,2026-03-26,2026-03-25,0.206822,0.213514,0.203890,0.187435,0.188339,0

### Portfolio performance view

In [8]:
_ = p4.port_view(fancy=True)

### Portfolio and its components relative performances

In [9]:
_ = p4.port_view_all(fancy=True)

## Portfolio performance in terms of total return, maximum drawdown, and RoMaD 

- `RR` - total rate of return
- `DD` - maximum drawdown
- `RoMaD` - return over maximum drawdown (`RR/DD`)
- `DD_date` - maximum drawdown date
- `DD_start` - maximum drawdate stating date
- `DD_end` - maximum drawdown ending date

In [10]:
p4.port_perf(fancy=True)

             RR     DD     RoMaD     DD_date    DD_start      DD_end  DD_days
symbol
UnivPort  12.36 -25.17  0.491307  2020-03-23  2020-02-19  2020-04-27       68
ONEQ      18.23 -35.23  0.517326  2022-12-28  2021-11-19  2024-01-29      801
SPY       14.89 -33.72  0.441738  2020-03-23  2020-02-19  2020-08-10      173
XLV       12.28 -28.40  0.432176  2020-03-23  2020-01-22  2020-07-15      175
VHT       12.37 -28.85  0.428857  2020-03-23  2020-02-19  2020-06-08      110
GLD        7.14 -42.11  0.169582  2015-12-17  2012-10-04  2020-07-22     2848

### Portfolio drawdowns (default - the first 5 largest)

- `DD` - value of the drawdown (percent)
- `Date` - drawdown date
- `Start` - drawdown starting date
- `End` - drawdown ending date

In [11]:
p4.port_drawdown(fancy=True)

       DD        Date       Start         End  NrDays
No
1  -25.17  2020-03-23  2020-02-19  2020-04-27      68
2  -19.02  2022-09-30  2021-12-30  2023-12-13     713
3  -14.10  2018-12-24  2018-10-02  2019-01-31     121
4  -13.29  2025-04-08  2025-02-20  2025-06-26     126
5  -13.01  2015-09-28  2015-07-16  2016-07-08     358

### Portfolio annual (calendar) rate of returns

>Note: the first and last year may not be a full calendar year.

In [12]:
p4.port_annual_returns(fancy=True)

### Portfolio monthly (clandar) rate of returns

In [13]:
p4.port_monthly_returns(fancy=True)

### Portfolio returns per reinvestment period 

- `Droll` - rolling date (rebalansing is assumed to be at the closing of the rolling date)
- `Dfinx` - fixing date (the most recent historical date included in the weights computations - last closing date)
- `RR` - portfolio rate of return on the rolling period starting on `Droll`
- *rest of the columns* - prevailing portfolio weights

In [14]:
p4.port_period_returns(fancy=True)

        Droll       Dfix     RR    VHT    SPY    XLV    GLD   ONEQ
0  2015-06-25 2015-06-24  -8.76  20.00  20.00  20.00  20.00  20.00
1  2015-09-25 2015-09-24   3.03  19.93  19.97  19.93  20.19  19.98
2  2015-12-28 2015-12-24  -0.27  19.97  20.09  20.01  19.85  20.09
3  2016-03-28 2016-03-24   2.17  19.74  20.12  19.84  20.34  19.96
4  2016-06-27 2016-06-24   6.51  19.76  20.04  19.84  20.52  19.84
5  2016-09-27 2016-09-26  -1.15  19.76  20.04  19.81  20.36  20.03
6  2016-12-27 2016-12-23   7.43  19.72  20.34  19.77  19.90  20.27
7  2017-03-28 2017-03-27   4.38  19.74  20.22  19.78  20.00  20.25
8  2017-06-27 2017-06-26   2.12  19.84  20.19  19.86  19.79  20.30
9  2017-09-26 2017-09-25   4.87  19.81  20.20  19.83  19.88  20.29
10 2017-12-26 2017-12-22   1.88  19.76  20.33  19.78  19.66  20.47
11 2018-03-26 2018-03-23   3.90  19.71  20.24  19.68  19.86  20.51
12 2018-06-26 2018-06-25   4.29  19.80  20.29  19.74  19.53  20.64
13 2018-09-25 2018-09-24 -10.00  19.96  20.33  19.92  19.17  20.63
14 2018-12-26 2018-12-24  15.45  19.86  20.11  19.90  19.86  20.27
15 2019-03-26 2019-03-25   0.77  19.85  20.25  19.83  19.55  20.52
16 2019-06-25 2019-06-24   0.38  19.78  20.27  19.78  19.62  20.54
17 2019-09-25 2019-09-24  10.12  19.68  20.28  19.68  19.85  20.52
18 2019-12-26 2019-12-24 -10.18  19.82  20.27  19.81  19.49  20.61
19 2020-03-26 2020-03-25  23.16  19.60  19.95  19.61  20.32  20.51
20 2020-06-25 2020-06-24   2.62  19.64  19.99  19.56  19.96  20.85
21 2020-09-25 2020-09-24  11.37  19.58  20.02  19.51  19.96  20.93
22 2020-12-28 2020-12-24   1.13  19.64  20.10  19.46  19.61  21.19
23 2021-03-26 2021-03-25   8.53  19.66  20.27  19.54  19.32  21.20
24 2021-06-25 2021-06-24   1.99  19.69  20.30  19.57  19.15  21.29
25 2021-09-27 2021-09-24   4.71  19.72  20.33  19.63  18.99  21.33
26 2021-12-28 2021-12-27  -2.28  19.68  20.40  19.67  18.93  21.33
27 2022-03-28 2022-03-25  -9.67  19.63  20.35  19.69  19.28  21.06
28 2022-06-27 2022-06-24  -7.27  19.79  20.21  19.88  19.39  20.74
29 2022-09-27 2022-09-26   7.08  19.83  20.24  19.93  19.25  20.76
30 2022-12-27 2022-12-23   2.75  19.96  20.18  20.09  19.34  20.42
31 2023-03-28 2023-03-27   6.42  19.70  20.22  19.80  19.52  20.75
32 2023-06-27 2023-06-26  -1.08  19.63  20.33  19.72  19.29  21.02
33 2023-09-26 2023-09-25   7.78  19.59  20.36  19.73  19.29  21.03
34 2023-12-26 2023-12-22   9.47  19.49  20.43  19.60  19.26  21.22
35 2024-03-25 2024-03-22   4.02  19.46  20.50  19.60  19.18  21.26
36 2024-06-25 2024-06-24   6.10  19.37  20.50  19.51  19.27  21.35
37 2024-09-25 2024-09-24  -0.18  19.34  20.47  19.47  19.49  21.24
38 2024-12-26 2024-12-24   1.40  19.06  20.67  19.17  19.44  21.65
39 2025-03-26 2025-03-25   2.43  19.12  20.47  19.27  19.87  21.27
40 2025-06-25 2025-06-24   8.40  18.85  20.58  18.96  20.11  21.50
41 2025-09-25 2025-09-24  11.66  18.71  20.61  18.79  20.22  21.67
42 2025-12-26 2025-12-24  -5.41  18.80  20.39  18.88  20.48  21.45
43 2026-03-26 2026-03-25   5.25  18.74  20.39  18.83  20.68  21.35

### Number of shares per portfolio component for each rolling period

In [15]:
p4.get_nshares()

            GLD  ONEQ  SPY  VHT  XLV  _CASH_
Droll
2015-06-25  178   994   95  141  264       0
2015-09-25  167   985   95  142  266       0
2015-12-28  184   969   94  143  264       0
2016-03-28  165  1008   94  153  278       0
2016-06-27  157  1028   95  151  276       0
2016-09-27  165  1004   97  154  284       0
2016-12-27  186   951   91  156  287       0
2017-03-28  181   955   94  155  288       0
2017-06-27  189   936   94  150  280       0
2017-09-26  187   947   95  153  285       0
2017-12-26  198   912   93  156  291       0
2018-03-26  192   925   97  162  305       0
2018-06-26  205   880   94  155  296       0
2018-09-25  227   885   94  150  284       0
2018-12-26  200  1008  104  160  298       0
2019-03-26  211   925   98  157  295       0
2019-06-25  205   914   97  159  297       0
2019-09-25  195   926   97  164  308       0
2019-12-26  215   923   99  160  300       0
2020-03-26  187   993  113  178  335       0
2020-06-25  198   889  108  171  329       0
2020-09-25  199   882  108  175  337       0
2020-12-28  216   826  106  172  339       0
2021-03-26  236   834  103  173  337       0
2021-06-25  245   811  102  171  333       0
2021-09-27  254   798  100  167  325       0
2021-12-28  259   800   99  171  324       0
2022-03-28  239   859  101  175  326       0
2022-06-27  231   926  105  168  312       0
2022-09-27  240   924  105  167  309       0
2022-12-27  234  1004  106  162  298       0
2023-03-28  223   937  106  174  322       0
2023-06-27  239   888  104  179  332       0
2023-09-26  236   876  102  178  328       0
2023-12-26  241   853  103  187  345       0
2024-03-25  245   841  101  187  345       0
2024-06-25  239   829  101  192  355       0
2024-09-25  225   847  102  194  359       0
2024-12-26  229   782   98  211  392       0
2025-03-26  205   849  102  207  381       0
2025-06-25  195   816  101  226  421       0
2025-09-25  188   781   99  234  439       0
2025-12-26  179   830  106  233  435       0
2026-03-26  167   832  104  232  433       0

### Other accounting informations

- `Droll` - the start of the rolling period (the end is the next period starting date)
- *portfolio symbols* - number of shares per portfolio component
- `cash_invst` - Dollar equivalent of the shares on the `Droll` date
- `cash_roll` - amount of uninvested cash rolled to the next period. A negative value indicates that the investor need to add this cash amount in order to execute the rolling. The main reasons for these small cash amounts are shares price differential between the fixing (computations) and rolling (execution) dates, as well as rounding to an integer the number of shares.
- `cash_divd` - amount of cash collected form dividend payments during the rolling period (it is an approximation considering the ex-dividend day as the dividend pay day - in practice between these dates could be a gap of a few days or even few weeks).

Note: the value of `cash_roll` can be minimized if,
1. set fixing date to be the same as the rolling date (implies the ability to run the portfolio optimization and execute the rolling transactions close to the end of trading day)
2. a large initial capital will lower, in a relative bases, the impact of rounding to an integer the number of shares.

In [16]:
p4.get_account(fancy=True)

,GLD,ONEQ,SPY,VHT,XLV,_CASH_,cash_invst,cash_roll,cash_divd
Droll,,,,,,,,,
2015-06-25,178.0,994.0,95.0,141.0,264.0,0.0,100108.56,-108.56,0.00
2015-09-25,167.0,985.0,95.0,142.0,266.0,0.0,90224.22,1384.62,377.90
2015-12-28,184.0,969.0,94.0,143.0,264.0,0.0,95317.45,441.72,263.33
2016-03-28,165.0,1008.0,94.0,153.0,278.0,0.0,94531.22,38.67,270.22
2016-06-27,157.0,1028.0,95.0,151.0,276.0,0.0,95055.63,1176.42,300.63
2016-09-27,165.0,1004.0,97.0,154.0,284.0,0.0,104064.59,-433.69,318.73
2016-12-27,186.0,951.0,91.0,156.0,287.0,0.0,101207.54,-311.44,368.05
2017-03-28,181.0,955.0,94.0,155.0,288.0,0.0,108601.55,-176.31,275.03
2017-06-27,189.0,936.0,94.0,150.0,280.0,0.0,112326.15,971.65,260.07
2017-09-26,187.0,947.0,95.0,153.0,285.0,0.0,116749.66,159.39,326.73
2017-12-26,198.0,912.0,93.0,156.0,291.0,0.0,122049.10,-193.10,461.14
2018-03-26,192.0,925.0,97.0,162.0,305.0,0.0,126233.04,-2623.21,289.98
2018-06-26,205.0,880.0,94.0,155.0,296.0,0.0,125846.33,140.79,283.84
2018-09-25,227.0,885.0,94.0,150.0,284.0,0.0,134470.02,-5.11,487.11
2018-12-26,200.0,1008.0,104.0,160.0,298.0,0.0,125589.67,-4727.36,414.59
2019-03-26,211.0,925.0,98.0,157.0,295.0,0.0,135452.42,-648.01,472.33
2019-06-25,205.0,914.0,97.0,159.0,297.0,0.0,139227.64,789.26,532.99
2019-09-25,195.0,926.0,97.0,164.0,308.0,0.0,141472.69,320.86,333.02
2019-12-26,215.0,923.0,99.0,160.0,300.0,0.0,156696.08,-597.49,876.10
2020-03-26,187.0,993.0,113.0,178.0,335.0,0.0,146616.57,-7469.49,607.86
2020-06-25,198.0,889.0,108.0,171.0,329.0,0.0,165675.71,-1280.97,503.79
2020-09-25,199.0,882.0,108.0,175.0,337.0,0.0,177350.38,-2308.82,470.93
2020-12-28,216.0,826.0,106.0,172.0,339.0,0.0,194844.05,-726.57,573.17
2021-03-26,236.0,834.0,103.0,173.0,337.0,0.0,200523.48,-2754.71,430.82
2021-06-25,245.0,811.0,102.0,171.0,333.0,0.0,213759.65,-1061.20,483.97
2021-09-27,254.0,798.0,100.0,167.0,325.0,0.0,217029.07,1537.73,371.72
2021-12-28,259.0,800.0,99.0,171.0,324.0,0.0,230996.79,833.98,707.62
2022-03-28,239.0,859.0,101.0,175.0,326.0,0.0,226290.17,-641.41,452.72
2022-06-27,231.0,926.0,105.0,168.0,312.0,0.0,202396.69,167.40,536.17
2022-09-27,240.0,924.0,105.0,167.0,309.0,0.0,188619.82,-105.80,418.05
2022-12-27,234.0,1004.0,106.0,162.0,298.0,0.0,201112.84,797.08,788.01
2023-03-28,223.0,937.0,106.0,174.0,322.0,0.0,207520.10,571.79,528.72
2023-06-27,239.0,888.0,104.0,179.0,332.0,0.0,221931.03,-883.19,432.48
2023-09-26,236.0,876.0,102.0,178.0,328.0,0.0,214915.20,2460.62,589.70
2023-12-26,241.0,853.0,103.0,187.0,345.0,0.0,239209.13,-1345.57,804.08
2024-03-25,245.0,841.0,101.0,187.0,345.0,0.0,255800.88,118.28,453.90
2024-06-25,239.0,829.0,101.0,192.0,355.0,0.0,267831.19,-102.30,463.65
2024-09-25,225.0,847.0,102.0,194.0,359.0,0.0,283030.23,973.45,660.33
2024-12-26,229.0,782.0,98.0,211.0,392.0,0.0,285381.00,-488.65,970.81
2025-03-26,205.0,849.0,102.0,207.0,381.0,0.0,284573.06,2498.61,657.19
2025-06-25,195.0,816.0,101.0,226.0,421.0,0.0,297675.00,-772.92,519.83
2025-09-25,188.0,781.0,99.0,234.0,439.0,0.0,316170.12,2641.83,1020.66
2025-12-26,179.0,830.0,106.0,233.0,435.0,0.0,360408.17,-1081.83,990.15
2026-03-26,167.0,832.0,104.0,232.0,433.0,0.0,329943.43,6182.45,773.04

# Universal Portfolio - weights evaluation on a fixing date

This is an example of how to evaluate efficiently the portfolio weights in a fixing date.
It follow a similar procedure as any other portfolio weights evaluation.

We will reuse the `mktdata` previously collected in cell [3].

We star by setting the universal portfolio from a fixing schedule. Later will do a similar computation where the universal portfolio will be set from a hard given fixing date.

### Set a fixing schedule 

For Universal portfolio, the computations of the weights in the fixing date requires the knowledge of all the previous 
fixing dates (as well as market data on these dates). We accomplish this by using `azapy.schedule_simple` function.

- `sdate` - start date of available historical data. The schedule start date will be greater but as close is possible to this date. 
- `edate`- end date of available historical data. The schedule end date is smaller but as close is possible to this date.
- `freq` - fixing frequency. It could be `M` for monthly or `Q` for quarterly.
- `noffset` - rolling date offset - number of business days offset form the last business day of the period (monthly or quarterly).
- `fixoffset` - fixing date offset in business days relative to the rolling date

In [17]:
fixing_schedule = az.schedule_simple(sdate, edate, 
                                     freq='M', noffset=-5, fixoffset=0)
fixing_schedule

         Droll       Dfix
0   2012-01-24 2012-01-24
1   2012-02-22 2012-02-22
2   2012-03-23 2012-03-23
3   2012-04-23 2012-04-23
4   2012-05-23 2012-05-23
..         ...        ...
168 2026-01-23 2026-01-23
169 2026-02-20 2026-02-20
170 2026-03-24 2026-03-24
171 2026-04-23 2026-04-23
172 2026-05-21 2026-05-21

[173 rows x 2 columns]

## Set the `azapy.UniversalEngine` class from a fixing schedule

Alternatively, the UniversalEngine object can be set from a hard given fixing date (we will use this approach later in this script).

In [18]:
puniv = az.UniversalEngine(mktdata, schedule=fixing_schedule)

### Compute the portfolio weights

- `mc_paths` - are the number of simulations per batch (must be >= 1)
- `nr_batches` - are the number of batches (must be >= 1). Note that the computation is multithreaded with one batch per thread.
- `variance_reduction = True` - default value (the MC will use the antithetic variance reduce implied by the permutations of the basket components)
- `alpha_dirichlet = None` - default value. In this case a uniform random generator of vectors in the M-simplex is used. This is equivalent to a Flat Dirichlet random generator (all alpha set to 1).
- `mc_seed` - random generator seed value
- `verbose` - print out
    * number of MC simulations (`mc_paths * nr_batches * M!` if `variance_reduction = True` and `mc_paths * nr_batches` otherwise, where `M` is the number of portfolio components and `M!` its factorial).
    * simulation time
    
>Note: if `variance_reduction = True` (the default value) then both the effective number of MC simulations and the computation time grow factorial with the number of portfolio components. For large portfolios it is recommended to the impact of this setup.

>Note: multithreading under Python implementation has reduced effect. In our case we get a time reduction around 30%

In [19]:

ww = puniv.getWeights(mc_paths=100, nr_batches=16, mc_seed=42, finalonly=False, verbose=True)

nr simulations: 192000
simulation time: 0.476893

### New portfolio weights

These are in the last raw of `ww`.

>Note: `ww` includes all historical weights (along the fixing schedule) - `finalonly` was set to `False`

In [20]:
ww

symbol           GLD      ONEQ       SPY       VHT       XLV
date
2012-01-24  0.200000  0.200000  0.200000  0.200000  0.200000
2012-02-22  0.201024  0.200564  0.199959  0.199372  0.199082
2012-03-23  0.198416  0.201700  0.200611  0.199814  0.199459
2012-04-23  0.198236  0.201023  0.200248  0.200346  0.200146
2012-05-23  0.197746  0.200785  0.200231  0.200747  0.200490
...              ...       ...       ...       ...       ...
2025-12-23  0.178412  0.219568  0.205125  0.198463  0.198432
2026-01-23  0.180672  0.218593  0.204400  0.198132  0.198205
2026-02-20  0.181459  0.217775  0.204577  0.197967  0.198222
2026-03-24  0.179486  0.218804  0.205448  0.198033  0.198229
2026-04-23  0.179577  0.221076  0.206156  0.196619  0.196572

[172 rows x 5 columns]

## Set the `azapy.UniversalEngine` class

### Build the UniversalEngine object

The fixing schedule is build internally going backward from the fixing date with a step of either 21 (for `freq='M'`) or 63 (for `freq='Q'`). The resulting schedule is approximatively equivalent with the one returned by `azapy.shedule_simple` function (that is using a business calendar and in general is more sophisticated).

In [21]:
puniv2 = az.UniversalEngine(mktdata, freq='M')

###  Weights computation - same as before

In [22]:
ww = puniv2.getWeights(mc_paths=100, nr_batches=16, mc_seed=42, verbose=True)
print(ww)

nr simulations: 192000

simulation time: 0.457964
symbol
GLD     0.196523
ONEQ    0.217920
SPY     0.205174
VHT     0.189786
XLV     0.190596
Name: 2026-04-30 00:00:00, dtype: float64

## Set the `azapy.UniversalEngine` class with a Dirichlet random generator

We start by defining the Dirichlet alpha coefficient (must be between 0 and 1)

Here we choose all to be equal to the inverse of the number of portfolio components

In [23]:
dirichlet_alpha = [1 / len(symb)] * len(symb)

### Computation of the weights 

We start by passing the `dirichlet_alpha` coefficients to the constructor.

The rest is the same a above.

>Note: setting all alpha to 1 is equivalent to using a uniform random generator of vectors in the M-simplex of portfolio weights.

In [24]:
puniv2 = az.UniversalEngine(mktdata, freq='M', dirichlet_alpha=dirichlet_alpha)
ww = puniv2.getWeights(mc_paths=100, nr_batches=16, mc_seed=42, verbose=True)
print(ww)

nr simulations: 192000
simulation time: 0.435749
symbol
GLD     0.185432
ONEQ    0.255355
SPY     0.214970
VHT     0.171095
XLV     0.173148
Name: 2026-04-30 00:00:00, dtype: float64